global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # VTT Server metrics
  - job_name: 'vtt-server'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # VTT Client metrics (if available)
  - job_name: 'vtt-client'
    static_configs:
      - targets: ['client:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Custom VTT business metrics
  - job_name: 'vtt-business-metrics'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/api/metrics/business'
    scrape_interval: 60s
    honor_labels: true

  # VTT Health Check Probes
  - job_name: 'vtt-health-check'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/probe'
    params:
      module: [http_2xx]
      target: ['http://server:8080/api/health']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # VTT Liveness Probe
  - job_name: 'vtt-liveness'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/probe'
    params:
      module: [http_2xx]
      target: ['http://server:8080/api/health/live']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # VTT Readiness Probe
  - job_name: 'vtt-readiness'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/probe'
    params:
      module: [http_2xx]
      target: ['http://server:8080/api/health/ready']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
