apiVersion: v1
kind: ConfigMap
metadata:
  name: vtt-config
  labels:
    app.kubernetes.io/name: vtt-config
    app.kubernetes.io/part-of: vtt

data:
  # --- Server HTTP config ---
  PORT: "8080"
  JSON_LIMIT_BYTES: "1000000"

  # CORS configuration
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,OPTIONS,PUT,DELETE"
  CORS_HEADERS: "Content-Type,Authorization,X-Trace-ID,X-Request-ID"

  # Security headers
  HSTS: "true"
  CSP: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: https:; font-src 'self' data: https:"

  # Rate limiting (token bucket per IP)
  RATE_LIMIT_WINDOW_MS: "1000"
  RATE_LIMIT_MAX: "50"

  # WebSocket simulation toggles (server-side ECS demo)
  SIM_ENABLE: "false"
  SIM_N: "1000"
  SIM_BOUNDS: "2000"
  SIM_TICK: "12"

  # Cloud-agnostic external endpoints (to be overridden by environment)
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio:9000"
  
  # Environment indicator
  NODE_ENV: "production"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Health check configuration
  HEALTH_CHECK_TIMEOUT: "5000"
  HEALTH_CHECK_INTERVAL: "30000"
  
  # Cache configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "100"
  
  # Session configuration
  SESSION_SECRET: "default-session-secret-change-in-production"
  SESSION_MAX_AGE: "86400000"
  
  # File upload limits
  MAX_FILE_SIZE: "52428800"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/gif,image/webp,audio/mpeg,audio/wav,video/mp4"
  
  # AI provider defaults
  AI_DEFAULT_TIMEOUT: "30000"
  AI_DEFAULT_MAX_RETRIES: "3"
  AI_DEFAULT_RATE_LIMIT: "60"
