apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vtt-ingress
  labels:
    app.kubernetes.io/name: vtt-ingress
    app.kubernetes.io/part-of: vtt
  annotations:
    # Generic ingress annotations that work across cloud providers
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    
    # Rate limiting (cloud-agnostic)
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: https:; font-src 'self' data: https:";

spec:
  # TLS configuration - certificate management handled by cert-manager
  tls:
    - hosts:
        - "${VTT_DOMAIN_NAME}"
      secretName: vtt-tls-secret
  
  rules:
    - host: "${VTT_DOMAIN_NAME}"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vtt-client-service
                port:
                  number: 3000

---
# Fallback ingress for local development
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vtt-ingress-local
  labels:
    app.kubernetes.io/name: vtt-ingress-local
    app.kubernetes.io/part-of: vtt
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vtt-client-service
                port:
                  number: 3000
    - host: "vtt.local"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: vtt-server-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vtt-client-service
                port:
                  number: 3000
