apiVersion: v1
kind: Secret
metadata:
  name: vtt-secrets
  labels:
    app.kubernetes.io/part-of: vtt
type: Opaque
stringData:
  # Required infrastructure secrets
  DATABASE_URL: ""
  MINIO_ROOT_USER: ""
  MINIO_ROOT_PASSWORD: ""

  # AI provider keys (all optional for maximum flexibility)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""
  OPENROUTER_API_KEY: ""
  STABILITY_API_KEY: ""
  REPLICATE_API_TOKEN: ""
  HUGGINGFACE_API_KEY: ""
  
  # OAuth and authentication secrets
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  
  # Session and JWT secrets
  SESSION_SECRET: ""
  JWT_SECRET: ""
  
  # Additional service secrets
  WEBHOOK_SECRET: ""
  ENCRYPTION_KEY: ""
