export const LEVEL_9_SPELLS = {
  astralProjection: {
    id: "astral_projection",
    name: "Astral Projection",
    level: 9,
    school: "necromancy",
    castingTime: "1 hour",
    range: "10 feet",
    components: ["V", "S", "M"],
    materialComponent:
      "for each creature affected by this spell, you must provide one jacinth worth at least 1,000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes",
    duration: "Special",
    description:
      "You and up to eight willing creatures within range project your astral bodies into the Astral Plane (the spell fails and the casting is wasted if you are already on that plane).",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "astral_plane", "projection", "multiple_targets", "costly_components"],
  },
  foresight: {
    id: "foresight",
    name: "Foresight",
    level: 9,
    school: "divination",
    castingTime: "1 minute",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "a hummingbird feather",
    duration: "8 hours",
    description:
      "You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can't be surprised and has advantage on attack rolls, ability checks, and saving throws.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Druid", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["divination", "foresight", "advantage", "surprise_immunity", "long_duration"],
  },
  gate: {
    id: "gate",
    name: "Gate",
    level: 9,
    school: "conjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a diamond worth at least 5,000 gp",
    duration: "Concentration, up to 1 minute",
    description:
      "You conjure a portal linking an unoccupied space you can see within range to a precise location on a different plane of existence.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["conjuration", "portal", "planar_travel", "concentration", "costly_components"],
  },
  imprisonment: {
    id: "imprisonment",
    name: "Imprisonment",
    level: 9,
    school: "abjuration",
    castingTime: "1 minute",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent:
      "a vellum depiction or a carved statuette in the likeness of the target, and a special component that varies according to the version of the spell you choose, worth at least 500 gp per Hit Die of the target",
    duration: "Until dispelled",
    description:
      "You create a magical restraint to hold a creature that you can see within range. The target must succeed on a Wisdom saving throw or be bound by the spell.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: [
      "abjuration",
      "imprisonment",
      "wisdom_save",
      "permanent",
      "costly_components",
      "multiple_forms",
    ],
  },
  massHeal: {
    id: "mass_heal_9th",
    name: "Mass Heal",
    level: 9,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range.",
    concentration: false,
    ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["healing", "mass_effect", "high_healing", "multiple_targets", "condition_removal"],
  },
  meteorSwarm: {
    id: "meteor_swarm",
    name: "Meteor Swarm",
    level: 9,
    school: "evocation",
    castingTime: "1 action",
    range: "1 mile",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point you choose must make a Dexterity saving throw.",
    damage: { diceExpression: "20d6", damageType: "fire", scalingDice: "0" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: [
      "damage",
      "fire",
      "bludgeoning",
      "dexterity_save",
      "multiple_spheres",
      "extreme_range",
      "massive_damage",
    ],
  },
  powerWordKill: {
    id: "power_word_kill",
    name: "Power Word Kill",
    level: 9,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["enchantment", "power_word", "instant_death", "hit_point_threshold", "no_save"],
  },
  prismaticWall: {
    id: "prismatic_wall",
    name: "Prismatic Wall",
    level: 9,
    school: "abjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "10 minutes",
    description:
      "A shimmering, multicolored plane of light forms a vertical opaque wall—up to 90 feet long, 30 feet high, and 1 inch thick—centered on a point you can see within range.",
    concentration: false,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["abjuration", "wall", "prismatic", "multiple_layers", "varied_effects", "barrier"],
  },
  shapechange: {
    id: "shapechange",
    name: "Shapechange",
    level: 9,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent:
      "a jade circlet worth at least 1,500 gp, which you must place on your head before you cast the spell",
    duration: "Concentration, up to 1 hour",
    description:
      "You assume the form of a different creature for the duration. The new form can be any creature with a challenge rating equal to your level or lower.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "shapechange", "any_creature", "concentration", "costly_components"],
  },
  stormOfVengeance: {
    id: "storm_of_vengeance",
    name: "Storm of Vengeance",
    level: 9,
    school: "conjuration",
    castingTime: "1 action",
    range: "Sight",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "A churning storm cloud forms, centered on a point you can see and spreading to a radius of 360 feet.",
    concentration: true,
    ritual: false,
    classes: ["Druid"],
    source: "SRD 5.1",
    tags: [
      "conjuration",
      "storm",
      "multiple_effects",
      "massive_area",
      "concentration",
      "escalating",
    ],
  },
  timeStop: {
    id: "time_stop",
    name: "Time Stop",
    level: 9,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "You briefly stop the flow of time for everyone but yourself. No time passes for other creatures, while you take 1d4 + 1 turns in a row.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "time_manipulation", "extra_turns", "temporal"],
  },
  truePolymorph: {
    id: "true_polymorph",
    name: "True Polymorph",
    level: 9,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent: "a drop of mercury, a dollop of gum arabic, and a wisp of smoke",
    duration: "Concentration, up to 1 hour",
    description:
      "Choose one creature or nonmagical object that you can see within range. You transform the creature into a different creature, the creature into an object, or the object into a creature.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: [
      "transmutation",
      "polymorph",
      "permanent_potential",
      "wisdom_save",
      "concentration",
      "versatile",
    ],
  },
  trueResurrection: {
    id: "true_resurrection",
    name: "True Resurrection",
    level: 9,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes",
    duration: "Instantaneous",
    description:
      "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Druid"],
    source: "SRD 5.1",
    tags: [
      "necromancy",
      "resurrection",
      "ultimate_restoration",
      "costly_components",
      "body_recreation",
    ],
  },
  weird: {
    id: "weird",
    name: "Weird",
    level: 9,
    school: "illusion",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "Drawing on the deepest fears of a group of creatures, you create illusory creatures in their minds, visible only to them.",
    damage: { diceExpression: "4d10", damageType: "psychic", scalingDice: "0" },
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["illusion", "fear", "psychic", "wisdom_save", "concentration", "multiple_targets"],
  },
  wish: {
    id: "wish",
    name: "Wish",
    level: 9,
    school: "conjuration",
    castingTime: "1 action",
    range: "Self",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["conjuration", "wish", "reality_alteration", "ultimate_power", "stress_risk"],
  },
};
//# sourceMappingURL=level9.js.map
