export const LEVEL_8_SPELLS = {
  antimagicField: {
    id: "antimagic_field",
    name: "Antimagic Field",
    level: 8,
    school: "abjuration",
    castingTime: "1 action",
    range: "Self (10-foot radius sphere)",
    components: ["V", "S", "M"],
    materialComponent: "a pinch of powdered iron or iron filings",
    duration: "Concentration, up to 1 hour",
    description:
      "A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["abjuration", "antimagic", "sphere", "concentration", "magic_suppression"],
  },
  clone: {
    id: "clone",
    name: "Clone",
    level: 8,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold a Medium creature, such as a large urn, coffin, or something similar",
    duration: "Instantaneous",
    description:
      "This spell grows an inert duplicate of a living creature as a safeguard against death.",
    concentration: false,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "clone", "backup_body", "costly_components", "long_casting"],
  },
  controlWeather: {
    id: "control_weather",
    name: "Control Weather",
    level: 8,
    school: "transmutation",
    castingTime: "10 minutes",
    range: "Self (5-mile radius)",
    components: ["V", "S", "M"],
    materialComponent: "burning incense and bits of earth and wood mixed in water",
    duration: "Concentration, up to 8 hours",
    description:
      "You take control of the weather within 5 miles of you for the duration. You must be outdoors to cast this spell.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Druid", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "weather", "large_area", "concentration", "environmental"],
  },
  dominateMonster: {
    id: "dominate_monster",
    name: "Dominate Monster",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 hour",
    description:
      "You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["control", "charm", "any_creature", "wisdom_save", "concentration"],
    upcastDescription:
      "When you cast this spell with a 9th-level spell slot, the duration is concentration, up to 8 hours.",
  },
  earthquake: {
    id: "earthquake",
    name: "Earthquake",
    level: 8,
    school: "evocation",
    castingTime: "1 action",
    range: "500 feet",
    components: ["V", "S", "M"],
    materialComponent: "a pinch of dirt, a piece of rock, and a lump of clay",
    duration: "Concentration, up to 1 minute",
    description:
      "You create a seismic disturbance at a point on the ground that you can see within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point.",
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Druid", "Sorcerer"],
    source: "SRD 5.1",
    tags: [
      "evocation",
      "earthquake",
      "dexterity_save",
      "large_area",
      "concentration",
      "terrain_destruction",
    ],
  },
  feeblemind: {
    id: "feeblemind",
    name: "Feeblemind",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "a handful of clay, crystal, glass, or mineral spheres",
    duration: "Instantaneous",
    description:
      "You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality.",
    damage: { diceExpression: "4d6", damageType: "psychic", scalingDice: "0" },
    savingThrow: { ability: "INT", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Druid", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["enchantment", "feeblemind", "intelligence_save", "ability_damage", "incapacitation"],
  },
  holyAura: {
    id: "holy_aura",
    name: "Holy Aura",
    level: 8,
    school: "abjuration",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent:
      "a tiny reliquary worth at least 1,000 gp containing a sacred relic, such as a scrap of cloth from a saint's robe or a piece of parchment from a religious text",
    duration: "Concentration, up to 1 minute",
    description:
      "Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you.",
    concentration: true,
    ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["abjuration", "holy", "advantage", "resistance", "concentration", "costly_components"],
  },
  incendiaryCloud: {
    id: "incendiary_cloud",
    name: "Incendiary Cloud",
    level: 8,
    school: "conjuration",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "A swirling cloud of smoke shot through with white-hot embers appears in a 20-foot-radius sphere centered on a point within range.",
    damage: { diceExpression: "10d8", damageType: "fire", scalingDice: "0" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "fire", "dexterity_save", "sphere", "concentration", "moving_cloud"],
  },
  maze: {
    id: "maze",
    name: "Maze",
    level: 8,
    school: "conjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 10 minutes",
    description:
      "You banish a creature that you can see within range into a labyrinthine demiplane.",
    savingThrow: { ability: "INT", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["conjuration", "banishment", "maze", "intelligence_check", "concentration"],
  },
  mindBlank: {
    id: "mind_blank",
    name: "Mind Blank",
    level: 8,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "24 hours",
    description:
      "Until the spell ends, one willing creature you touch is immune to any effect that would sense its emotions, read its thoughts, determine its location by divination magic, or determine its creature type.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Wizard"],
    source: "SRD 5.1",
    tags: ["abjuration", "mental_protection", "divination_immunity", "long_duration"],
  },
  powerWordStun: {
    id: "power_word_stun",
    name: "Power Word Stun",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["enchantment", "power_word", "stunning", "hit_point_threshold", "no_save"],
  },
  sunburst: {
    id: "sunburst",
    name: "Sunburst",
    level: 8,
    school: "evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "fire and a piece of sunstone",
    duration: "Instantaneous",
    description:
      "Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range.",
    damage: { diceExpression: "12d6", damageType: "radiant", scalingDice: "0" },
    savingThrow: { ability: "CON", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "radiant", "constitution_save", "sphere", "blindness", "undead_vulnerability"],
  },
  antimagicField: {
    id: "antimagic_field",
    name: "Antimagic Field",
    level: 8,
    school: "abjuration",
    castingTime: "1 action",
    range: "Self (10-foot radius)",
    components: ["V", "S", "M"],
    materialComponent: "a pinch of powdered iron or iron filings",
    duration: "Concentration, up to 1 hour",
    description: "A 10-foot-radius invisible sphere of antimagic surrounds you.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["abjuration", "antimagic", "sphere", "magic_suppression", "concentration"],
  },
  clone: {
    id: "clone",
    name: "Clone",
    level: 8,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp",
    duration: "Instantaneous",
    description:
      "This spell grows an inert duplicate of a living creature as a safeguard against death.",
    concentration: false,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "cloning", "backup_body", "costly_components", "long_casting"],
  },
  controlWeather: {
    id: "control_weather",
    name: "Control Weather",
    level: 8,
    school: "transmutation",
    castingTime: "10 minutes",
    range: "Self (5-mile radius)",
    components: ["V", "S", "M"],
    materialComponent: "burning incense and bits of earth and wood mixed in water",
    duration: "Concentration, up to 8 hours",
    description: "You take control of the weather within 5 miles of you for the duration.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Druid", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "weather", "environmental", "large_area", "concentration"],
  },
  feeblemind: {
    id: "feeblemind",
    name: "Feeblemind",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "a handful of clay, crystal, glass, or mineral spheres",
    duration: "Instantaneous",
    description:
      "You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality.",
    savingThrow: { ability: "INT", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Druid", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["enchantment", "intelligence_drain", "intelligence_save", "permanent"],
  },
};
//# sourceMappingURL=level8.js.map
