export const LEVEL_5_SPELLS = {
    animateDead: {
        id: "animate_dead",
        name: "Animate Dead",
        level: 5,
        school: "necromancy",
        castingTime: "1 minute",
        range: "10 feet",
        components: ["V", "S", "M"],
        materialComponent: "a drop of blood, a piece of flesh, and a pinch of bone dust",
        duration: "Instantaneous",
        description: "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature.",
        concentration: false,
        ritual: false,
        classes: ["Cleric", "Wizard"],
        source: "SRD 5.1",
        tags: ["necromancy", "undead", "minion", "control"],
        upcastDescription: "When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd.",
    },
    antilifeshell: {
        id: "antilife_shell",
        name: "Antilife Shell",
        level: 5,
        school: "abjuration",
        castingTime: "1 action",
        range: "Self (10-foot radius)",
        components: ["V", "S"],
        duration: "Concentration, up to 1 hour",
        description: "A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs.",
        concentration: true,
        ritual: false,
        classes: ["Druid"],
        source: "SRD 5.1",
        tags: ["protection", "barrier", "concentration", "living_creatures"],
    },
    cloudkill: {
        id: "cloudkill",
        name: "Cloudkill",
        level: 5,
        school: "conjuration",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
        description: "You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners.",
        damage: { diceExpression: "5d8", damageType: "poison", scalingDice: "1d8" },
        savingThrow: { ability: "CON", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "poison", "constitution_save", "sphere", "area", "concentration", "moving"],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.",
    },
    coneOfCold: {
        id: "cone_of_cold",
        name: "Cone of Cold",
        level: 5,
        school: "evocation",
        castingTime: "1 action",
        range: "Self (60-foot cone)",
        components: ["V", "S", "M"],
        materialComponent: "a small crystal or glass cone",
        duration: "Instantaneous",
        description: "A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw.",
        damage: { diceExpression: "8d8", damageType: "cold", scalingDice: "1d8" },
        savingThrow: { ability: "CON", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "cold", "constitution_save", "cone", "area"],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.",
    },
    conjureElemental: {
        id: "conjure_elemental",
        name: "Conjure Elemental",
        level: 5,
        school: "conjuration",
        castingTime: "1 minute",
        range: "90 feet",
        components: ["V", "S", "M"],
        materialComponent: "burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water",
        duration: "Concentration, up to 1 hour",
        description: "You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Wizard"],
        source: "SRD 5.1",
        tags: ["summoning", "elemental", "concentration", "powerful_minion"],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, the challenge rating increases by 1 for each slot level above 5th.",
    },
    dominatePerson: {
        id: "dominate_person",
        name: "Dominate Person",
        level: 5,
        school: "enchantment",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["control", "charm", "humanoid_only", "wisdom_save", "concentration"],
        upcastDescription: "When you cast this spell with a 6th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 7th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 8th level or higher, the duration is concentration, up to 8 hours.",
    },
    flamestrike: {
        id: "flame_strike",
        name: "Flame Strike",
        level: 5,
        school: "evocation",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "pinch of sulfur",
        duration: "Instantaneous",
        description: "A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw.",
        damage: { diceExpression: "4d6", damageType: "fire", scalingDice: "1d6" },
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["damage", "fire", "radiant", "dexterity_save", "cylinder", "area", "divine"],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, the fire damage or the radiant damage (your choice) increases by 1d6 for each slot level above 5th.",
    },
    greaterRestoration: {
        id: "greater_restoration",
        name: "Greater Restoration",
        level: 5,
        school: "abjuration",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "diamond dust worth at least 100 gp, which the spell consumes",
        duration: "Instantaneous",
        description: "You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target's exhaustion level by one, or end one of the following effects on the target: One effect that charmed or petrified the target, One curse, including the target's attunement to a cursed magic item, Any reduction to one of the target's ability scores, One effect reducing the target's hit point maximum.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid"],
        source: "SRD 5.1",
        tags: ["healing", "restoration", "condition_removal", "costly_components"],
    },
    holdMonster: {
        id: "hold_monster",
        name: "Hold Monster",
        level: 5,
        school: "enchantment",
        castingTime: "1 action",
        range: "90 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small, straight piece of iron",
        duration: "Concentration, up to 1 minute",
        description: "Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["control", "paralyzed", "wisdom_save", "concentration"],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th.",
    },
    insectPlague: {
        id: "insect_plague",
        name: "Insect Plague",
        level: 5,
        school: "conjuration",
        castingTime: "1 action",
        range: "300 feet",
        components: ["V", "S", "M"],
        materialComponent: "a few grains of sugar, some kernels of grain, and a smear of fat",
        duration: "Concentration, up to 10 minutes",
        description: "Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range.",
        damage: { diceExpression: "4d10", damageType: "piercing", scalingDice: "1d10" },
        savingThrow: { ability: "CON", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Druid", "Sorcerer"],
        source: "SRD 5.1",
        tags: [
            "damage",
            "piercing",
            "constitution_save",
            "sphere",
            "area",
            "concentration",
            "difficult_terrain",
        ],
        upcastDescription: "When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d10 for each slot level above 5th.",
    },
    massHeal: {
        id: "mass_heal",
        name: "Mass Heal",
        level: 5,
        school: "conjuration",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range.",
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["healing", "mass_effect", "high_healing", "multiple_targets"],
    },
    passwall: {
        id: "passwall",
        name: "Passwall",
        level: 5,
        school: "transmutation",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a pinch of sesame seeds",
        duration: "1 hour",
        description: "A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface within range.",
        concentration: false,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "movement", "wall_passage", "exploration"],
    },
    planarBinding: {
        id: "planar_binding",
        name: "Planar Binding",
        level: 5,
        school: "abjuration",
        castingTime: "1 hour",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a jewel worth at least 1,000 gp, which the spell consumes",
        duration: "24 hours",
        description: "With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to your service.",
        savingThrow: { ability: "CHA", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Wizard"],
        source: "SRD 5.1",
        tags: ["binding", "planar", "service", "charisma_save", "costly_components"],
        upcastDescription: "When you cast this spell using a spell slot of a higher level, the duration increases to 10 days with a 6th-level slot, to 30 days with a 7th-level slot, to 180 days with an 8th-level slot, and to a year and a day with a 9th-level spell slot.",
    },
    scrying: {
        id: "scrying",
        name: "Scrying",
        level: 5,
        school: "divination",
        castingTime: "10 minutes",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water",
        duration: "Concentration, up to 10 minutes",
        description: "You can see and hear a particular creature you choose that is on the same plane of existence as you.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: [
            "divination",
            "scrying",
            "remote_viewing",
            "wisdom_save",
            "concentration",
            "costly_components",
        ],
    },
    teleportationCircle: {
        id: "teleportation_circle",
        name: "Teleportation Circle",
        level: 5,
        school: "conjuration",
        castingTime: "1 minute",
        range: "10 feet",
        components: ["V", "M"],
        materialComponent: "rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes",
        duration: "1 round",
        description: "As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["teleportation", "circle", "permanent_link", "costly_components"],
    },
    wallOfStone: {
        id: "wall_of_stone",
        name: "Wall of Stone",
        level: 5,
        school: "evocation",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small block of granite",
        duration: "Concentration, up to 10 minutes",
        description: "A nonmagical wall of solid stone springs into existence at a point you choose within range.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["creation", "wall", "stone", "barrier", "concentration"],
    },
    awaken: {
        id: "awaken",
        name: "Awaken",
        level: 5,
        school: "transmutation",
        castingTime: "8 hours",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "an agate worth at least 1,000 gp, which the spell consumes",
        duration: "Instantaneous",
        description: "After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid"],
        source: "SRD 5.1",
        tags: ["transmutation", "awakening", "intelligence", "costly_components", "long_casting"],
    },
    commune: {
        id: "commune",
        name: "Commune",
        level: 5,
        school: "divination",
        castingTime: "1 minute",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "incense and a vial of holy or unholy water",
        duration: "1 minute",
        description: "You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no.",
        concentration: false,
        ritual: true,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["divination", "deity_contact", "questions", "ritual"],
    },
    communeWithNature: {
        id: "commune_with_nature",
        name: "Commune with Nature",
        level: 5,
        school: "divination",
        castingTime: "1 minute",
        range: "Self",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "You briefly become one with nature and gain knowledge of the surrounding territory.",
        concentration: false,
        ritual: true,
        classes: ["Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["divination", "nature", "knowledge", "terrain", "ritual"],
    },
    contactOtherPlane: {
        id: "contact_other_plane",
        name: "Contact Other Plane",
        level: 5,
        school: "divination",
        castingTime: "1 minute",
        range: "Self",
        components: ["V"],
        duration: "1 minute",
        description: "You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane.",
        savingThrow: { ability: "CHA", dc: 0 },
        concentration: false,
        ritual: true,
        classes: ["Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "planar_contact", "questions", "ritual", "risk"],
    },
    creation: {
        id: "creation",
        name: "Creation",
        level: 5,
        school: "illusion",
        castingTime: "1 minute",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a tiny piece of matter of the same type of the item you plan to create",
        duration: "Special",
        description: "You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range.",
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "creation", "shadow", "objects", "temporary"],
    },
    dispelEvilAndGood: {
        id: "dispel_evil_and_good",
        name: "Dispel Evil and Good",
        level: 5,
        school: "abjuration",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "holy water or powdered silver and iron",
        duration: "Concentration, up to 1 minute",
        description: "Shimmering energy surrounds and protects you from fey, undead, and creatures originating from beyond the Material Plane.",
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Paladin"],
        source: "SRD 5.1",
        tags: ["abjuration", "protection", "planar_creatures", "concentration"],
    },
    dream: {
        id: "dream",
        name: "Dream",
        level: 5,
        school: "illusion",
        castingTime: "1 minute",
        range: "Special",
        components: ["V", "S", "M"],
        materialComponent: "a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird",
        duration: "8 hours",
        description: "This spell shapes a creature's dreams. Choose a creature known to you as the target of this spell.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "dreams", "communication", "psychic_damage", "long_range"],
    },
    geasQuest: {
        id: "geas_quest",
        name: "Geas",
        level: 5,
        school: "enchantment",
        castingTime: "1 minute",
        range: "60 feet",
        components: ["V"],
        duration: "30 days",
        description: "You place a magical command on a creature that you can see within range, forcing it to carry out some service or refrain from some action or course of activity as you decide.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Wizard"],
        source: "SRD 5.1",
        tags: ["enchantment", "command", "compulsion", "wisdom_save", "long_duration"],
        upcastDescription: "When you cast this spell using a spell slot of 7th or 8th level, the duration is 1 year. When you cast this spell using a spell slot of 9th level, the spell lasts until it is ended by one of the spells mentioned above.",
    },
    legend: {
        id: "legend_lore",
        name: "Legend Lore",
        level: 5,
        school: "divination",
        castingTime: "10 minutes",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each",
        duration: "Instantaneous",
        description: "Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "lore", "knowledge", "costly_components"],
    },
};
//# sourceMappingURL=level5.js.map