export const LEVEL_1_SPELLS = {
    bless: {
        id: "bless",
        name: "Bless",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a sprinkling of holy water",
        duration: "Concentration, up to 1 minute",
        description: "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.",
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Paladin"],
        source: "SRD 5.1",
        tags: ["buff", "attack_bonus", "save_bonus", "concentration"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    },
    burningHands: {
        id: "burning_hands",
        name: "Burning Hands",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "Self (15-foot cone)",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw.",
        damage: { diceExpression: "3d6", damageType: "fire", scalingDice: "1d6" },
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "fire", "dexterity_save", "cone"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    },
    alarm: {
        id: "alarm",
        name: "Alarm",
        level: 1,
        school: "abjuration",
        castingTime: "1 minute",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a tiny bell and a piece of fine silver wire",
        duration: "8 hours",
        description: "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube.",
        concentration: false,
        ritual: true,
        classes: ["Ranger", "Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "alarm", "detection", "ritual"],
    },
    animalFriendship: {
        id: "animal_friendship",
        name: "Animal Friendship",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a morsel of food",
        duration: "24 hours",
        description: "This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["enchantment", "beast", "wisdom_save", "charm"],
    },
    bane: {
        id: "bane",
        name: "Bane",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a drop of blood",
        duration: "Concentration, up to 1 minute",
        description: "Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.",
        savingThrow: { ability: "CHA", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Cleric"],
        source: "SRD 5.1",
        tags: ["debuff", "charisma_save", "concentration", "attack_penalty", "save_penalty"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    },
    charmPerson: {
        id: "charm_person",
        name: "Charm Person",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S"],
        duration: "1 hour",
        description: "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and it does so with advantage if you or your companions are fighting it.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["social", "charm", "wisdom_save"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    },
    cureWounds: {
        id: "cure_wounds",
        name: "Cure Wounds",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
        healing: { diceExpression: "1d8", scalingDice: "1d8" },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
        source: "SRD 5.1",
        tags: ["healing"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.",
    },
    detectMagic: {
        id: "detect_magic",
        name: "Detect Magic",
        level: 1,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
        description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic.",
        concentration: true,
        ritual: true,
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["detection", "concentration", "ritual"],
    },
    magicMissile: {
        id: "magic_missile",
        name: "Magic Missile",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
        damage: { diceExpression: "3d4+3", damageType: "force", scalingDice: "1d4+1" },
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "force", "auto_hit"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.",
    },
    shield: {
        id: "shield",
        name: "Shield",
        level: 1,
        school: "abjuration",
        castingTime: "1 reaction",
        range: "Self",
        components: ["V", "S"],
        duration: "1 round",
        description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["protection", "ac_bonus", "reaction"],
    },
    guidingBolt: {
        id: "guiding_bolt",
        name: "Guiding Bolt",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.",
        damage: { diceExpression: "4d6", damageType: "radiant", scalingDice: "1d6" },
        attackRoll: true,
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["damage", "radiant", "spell_attack", "advantage"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    },
    inflictWounds: {
        id: "inflict_wounds",
        name: "Inflict Wounds",
        level: 1,
        school: "necromancy",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.",
        damage: { diceExpression: "3d10", damageType: "necrotic", scalingDice: "1d10" },
        attackRoll: true,
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["damage", "necrotic", "melee_spell_attack"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.",
    },
    mageArmor: {
        id: "mage_armor",
        name: "Mage Armor",
        level: 1,
        school: "abjuration",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a piece of cured leather",
        duration: "8 hours",
        description: "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dex modifier.",
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["protection", "ac_base"],
    },
    healingWord: {
        id: "healing_word",
        name: "Healing Word",
        level: 1,
        school: "evocation",
        castingTime: "1 bonus action",
        range: "60 feet",
        components: ["V"],
        duration: "Instantaneous",
        description: "A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.",
        healing: { diceExpression: "1d4", scalingDice: "1d4" },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid"],
        source: "SRD 5.1",
        tags: ["healing", "bonus_action"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.",
    },
    faerieFire: {
        id: "faerie_fire",
        name: "Faerie Fire",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V"],
        duration: "Concentration, up to 1 minute",
        description: "Each object in a 20-foot cube within range is outlined in blue, green, or violet light. Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw.",
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Druid"],
        source: "SRD 5.1",
        tags: ["utility", "light", "advantage", "dexterity_save", "concentration"],
    },
    command: {
        id: "command",
        name: "Command",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V"],
        duration: "1 round",
        description: "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Cleric", "Paladin"],
        source: "SRD 5.1",
        tags: ["control", "wisdom_save", "compulsion"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional creature for each slot level above 1st.",
    },
    sanctuary: {
        id: "sanctuary",
        name: "Sanctuary",
        level: 1,
        school: "abjuration",
        castingTime: "1 bonus action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small silver mirror",
        duration: "1 minute",
        description: "You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["protection", "wisdom_save", "bonus_action"],
    },
    entangle: {
        id: "entangle",
        name: "Entangle",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "90 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain.",
        savingThrow: { ability: "STR", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Druid"],
        source: "SRD 5.1",
        tags: ["control", "restrained", "strength_save", "concentration", "area"],
    },
    expedititiousRetreat: {
        id: "expeditious_retreat",
        name: "Expeditious Retreat",
        level: 1,
        school: "transmutation",
        castingTime: "1 bonus action",
        range: "Self",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
        description: "This spell allows you to move at an incredible pace. When you cast this spell, and then as a bonus action on each of your turns until the spell ends, you can take the Dash action.",
        concentration: true,
        ritual: false,
        classes: ["Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "movement", "dash", "concentration", "bonus_action"],
    },
    falseLife: {
        id: "false_life",
        name: "False Life",
        level: 1,
        school: "necromancy",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a small amount of alcohol or distilled spirits",
        duration: "1 hour",
        description: "Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration.",
        concentration: false,
        ritual: false,
        classes: ["Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["necromancy", "temporary_hit_points", "self_buff"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you gain 5 additional temporary hit points for each slot level above 1st.",
    },
    featherFall: {
        id: "feather_fall",
        name: "Feather Fall",
        level: 1,
        school: "transmutation",
        castingTime: "1 reaction",
        range: "60 feet",
        components: ["V", "M"],
        materialComponent: "a small feather or piece of down",
        duration: "1 minute",
        description: "Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "reaction", "falling", "multiple_targets"],
    },
    findFamiliar: {
        id: "find_familiar",
        name: "Find Familiar",
        level: 1,
        school: "conjuration",
        castingTime: "1 hour",
        range: "10 feet",
        components: ["V", "S", "M"],
        materialComponent: "10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier",
        duration: "Instantaneous",
        description: "You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel.",
        concentration: false,
        ritual: true,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["conjuration", "familiar", "summon", "ritual", "costly_components"],
    },
    floatingDisk: {
        id: "floating_disk",
        name: "Floating Disk",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a drop of mercury",
        duration: "1 hour",
        description: "This spell creates a circular, horizontal plane of force, 3 feet in diameter and 1 inch thick, that floats 3 feet above the ground in an unoccupied space of your choice that you can see within range.",
        concentration: false,
        ritual: true,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "force", "carrying", "ritual"],
    },
    fogCloud: {
        id: "fog_cloud",
        name: "Fog Cloud",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 hour",
        description: "You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["conjuration", "fog", "obscurement", "concentration", "sphere"],
    },
    goodberry: {
        id: "goodberry",
        name: "Goodberry",
        level: 1,
        school: "transmutation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a sprig of mistletoe",
        duration: "Instantaneous",
        description: "Up to ten berries appear in your hand and are infused with magic for the duration. A creature can use its action to eat one berry.",
        concentration: false,
        ritual: false,
        classes: ["Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["transmutation", "healing", "food", "berries"],
    },
    grease: {
        id: "grease",
        name: "Grease",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a bit of pork rind or butter",
        duration: "1 minute",
        description: "Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into difficult terrain for the duration.",
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["conjuration", "grease", "difficult_terrain", "dexterity_save", "prone"],
    },
    heroism: {
        id: "heroism",
        name: "Heroism",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns.",
        concentration: true,
        ritual: false,
        classes: ["Bard", "Paladin"],
        source: "SRD 5.1",
        tags: ["buff", "fear_immunity", "temporary_hit_points", "concentration"],
    },
    hideousLaughter: {
        id: "hideous_laughter",
        name: "Hideous Laughter",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "tiny tarts and a feather that is waved in the air",
        duration: "Concentration, up to 1 minute",
        description: "A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Wizard"],
        source: "SRD 5.1",
        tags: ["control", "incapacitated", "wisdom_save", "concentration", "prone"],
    },
    huntersMark: {
        id: "hunters_mark",
        name: "Hunter's Mark",
        level: 1,
        school: "divination",
        castingTime: "1 bonus action",
        range: "90 feet",
        components: ["V"],
        duration: "Concentration, up to 1 hour",
        description: "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack.",
        damage: { diceExpression: "1d6", damageType: "varies", scalingDice: "0" },
        concentration: true,
        ritual: false,
        classes: ["Ranger"],
        source: "SRD 5.1",
        tags: ["divination", "mark", "weapon_damage", "tracking", "concentration", "bonus_action"],
    },
    identify: {
        id: "identify",
        name: "Identify",
        level: 1,
        school: "divination",
        castingTime: "1 minute",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a pearl worth at least 100 gp and an owl feather",
        duration: "Instantaneous",
        description: "You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them.",
        concentration: false,
        ritual: true,
        classes: ["Bard", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "identification", "magic_items", "ritual", "costly_components"],
    },
    illusoryScript: {
        id: "illusory_script",
        name: "Illusory Script",
        level: 1,
        school: "illusion",
        castingTime: "1 minute",
        range: "Touch",
        components: ["S", "M"],
        materialComponent: "a lead-based ink worth at least 10 gp, which the spell consumes",
        duration: "10 days",
        description: "You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration.",
        concentration: false,
        ritual: true,
        classes: ["Bard", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "writing", "deception", "ritual", "costly_components"],
    },
    longstrider: {
        id: "longstrider",
        name: "Longstrider",
        level: 1,
        school: "transmutation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a pinch of dirt",
        duration: "1 hour",
        description: "You touch a creature. The target's speed increases by 10 feet until the spell ends.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid", "Ranger", "Wizard"],
        source: "SRD 5.1",
        tags: ["transmutation", "movement", "speed", "buff"],
    },
    purifyFoodAndDrink: {
        id: "purify_food_and_drink",
        name: "Purify Food and Drink",
        level: 1,
        school: "transmutation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.",
        concentration: false,
        ritual: true,
        classes: ["Cleric", "Druid", "Paladin"],
        source: "SRD 5.1",
        tags: ["transmutation", "purification", "poison_removal", "disease_removal", "ritual"],
    },
    shieldOfFaith: {
        id: "shield_of_faith",
        name: "Shield of Faith",
        level: 1,
        school: "abjuration",
        castingTime: "1 bonus action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small parchment with a bit of holy text written on it",
        duration: "Concentration, up to 10 minutes",
        description: "A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Paladin"],
        source: "SRD 5.1",
        tags: ["abjuration", "armor_class", "bonus_action", "concentration"],
    },
    silentImage: {
        id: "silent_image",
        name: "Silent Image",
        level: 1,
        school: "illusion",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a bit of fleece",
        duration: "Concentration, up to 10 minutes",
        description: "You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube.",
        concentration: true,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "image", "visual", "concentration"],
    },
    sleep: {
        id: "sleep",
        name: "Sleep",
        level: 1,
        school: "enchantment",
        castingTime: "1 action",
        range: "90 feet",
        components: ["V", "S", "M"],
        materialComponent: "a pinch of fine sand, rose petals, or a cricket",
        duration: "1 minute",
        description: "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect.",
        damage: { diceExpression: "5d8", damageType: "none", scalingDice: "2d8" },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["enchantment", "sleep", "unconscious", "hit_point_based"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.",
    },
    speakWithAnimals: {
        id: "speak_with_animals",
        name: "Speak with Animals",
        level: 1,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S"],
        duration: "10 minutes",
        description: "You gain the ability to comprehend and verbally communicate with beasts for the duration.",
        concentration: false,
        ritual: true,
        classes: ["Bard", "Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["divination", "communication", "animals", "ritual"],
    },
    thunderwave: {
        id: "thunderwave",
        name: "Thunderwave",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "Self (15-foot cube)",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw.",
        damage: { diceExpression: "2d8", damageType: "thunder", scalingDice: "1d8" },
        savingThrow: { ability: "CON", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "thunder", "constitution_save", "area", "push"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.",
    },
    unseenServant: {
        id: "unseen_servant",
        name: "Unseen Servant",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a piece of string and a bit of wood",
        duration: "1 hour",
        description: "This spell creates an invisible, mindless, shapeless, Medium force that performs simple tasks at your command until the spell ends.",
        concentration: false,
        ritual: true,
        classes: ["Bard", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["conjuration", "servant", "force", "utility", "ritual"],
    },
    witchBolt: {
        id: "witch_bolt",
        name: "Witch Bolt",
        level: 1,
        school: "evocation",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a twig from a tree that has been struck by lightning",
        duration: "Concentration, up to 1 minute",
        description: "A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target.",
        damage: { diceExpression: "1d12", damageType: "lightning", scalingDice: "1d12" },
        attackRoll: true,
        concentration: true,
        ritual: false,
        classes: ["Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "lightning", "spell_attack", "concentration", "sustained"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the initial damage increases by 1d12 for each slot level above 1st.",
    },
    wrathfulSmite: {
        id: "wrathful_smite",
        name: "Wrathful Smite",
        level: 1,
        school: "evocation",
        castingTime: "1 bonus action",
        range: "Self",
        components: ["V"],
        duration: "Concentration, up to 1 minute",
        description: "The next time you hit with a melee weapon attack during this spell's duration, your attack deals an extra 1d6 psychic damage.",
        damage: { diceExpression: "1d6", damageType: "psychic" },
        concentration: true,
        ritual: false,
        classes: ["Paladin"],
        source: "SRD 5.1",
        tags: [
            "damage",
            "psychic",
            "weapon_enhancement",
            "concentration",
            "frightened",
            "bonus_action",
        ],
    },
    armorOfAgathys: {
        id: "armor_of_agathys",
        name: "Armor of Agathys",
        level: 1,
        school: "abjuration",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a cup of water",
        duration: "1 hour",
        description: "A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear.",
        concentration: false,
        ritual: false,
        classes: ["Warlock"],
        source: "SRD 5.1",
        tags: ["abjuration", "temporary_hit_points", "cold_damage", "protection", "retaliation"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, both the temporary hit points and the cold damage increase by 5 for each slot level above 1st.",
    },
    armsOfHadar: {
        id: "arms_of_hadar",
        name: "Arms of Hadar",
        level: 1,
        school: "conjuration",
        castingTime: "1 action",
        range: "Self (10-foot radius)",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you.",
        damage: { diceExpression: "2d6", damageType: "necrotic", scalingDice: "1d6" },
        savingThrow: { ability: "STR", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Warlock"],
        source: "SRD 5.1",
        tags: ["damage", "necrotic", "strength_save", "area", "restrained", "eldritch"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    },
    comprehendLanguages: {
        id: "comprehend_languages",
        name: "Comprehend Languages",
        level: 1,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a pinch of soot and salt",
        duration: "1 hour",
        description: "For the duration, you understand the literal meaning of any spoken language that you hear.",
        concentration: false,
        ritual: true,
        classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "language", "communication", "ritual", "utility"],
    },
    createOrDestroyWater: {
        id: "create_or_destroy_water",
        name: "Create or Destroy Water",
        level: 1,
        school: "transmutation",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a drop of water if creating water or a few grains of sand if destroying it",
        duration: "Instantaneous",
        description: "You either create or destroy water. Create Water: You create up to 10 gallons of clean water within range in an open container.",
        concentration: false,
        ritual: false,
        classes: ["Cleric", "Druid"],
        source: "SRD 5.1",
        tags: ["transmutation", "water", "creation", "destruction", "utility"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, you create or destroy 10 additional gallons of water for each slot level above 1st.",
    },
    divineSmite: {
        id: "divine_smite",
        name: "Divine Smite",
        level: 1,
        school: "evocation",
        castingTime: "1 bonus action",
        range: "Self",
        components: ["V"],
        duration: "Concentration, up to 1 minute",
        description: "The next time you hit with a melee weapon attack during the spell's duration, your weapon flares with white-hot intensity.",
        damage: { diceExpression: "2d6", damageType: "radiant", scalingDice: "1d6" },
        concentration: true,
        ritual: false,
        classes: ["Paladin"],
        source: "SRD 5.1",
        tags: ["damage", "radiant", "weapon_enhancement", "concentration", "bonus_action"],
        upcastDescription: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    },
    jump: {
        id: "jump",
        name: "Jump",
        level: 1,
        school: "transmutation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a grasshopper's hind leg",
        duration: "1 minute",
        description: "You touch a creature. The creature's jump distance is tripled until the spell ends.",
        concentration: false,
        ritual: false,
        classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["movement", "enhancement", "jump", "touch"],
    },
};
//# sourceMappingURL=level1.js.map