import type { SRDSpell } from '../spells';

export const LEVEL_6_SPELLS: Record<string, SRDSpell> = {
  chainLightning: {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    level: 6,
    school: 'evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins',
    duration: 'Instantaneous',
    description: 'You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets.',
    damage: { diceExpression: '10d8', damageType: 'lightning', scalingDice: '1d8' },
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'lightning', 'dexterity_save', 'chain', 'multiple_targets'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.'
  },

  circleOfDeath: {
    id: 'circle_of_death',
    name: 'Circle of Death',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'the powder of a crushed black pearl worth at least 500 gp',
    duration: 'Instantaneous',
    description: 'A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range. Each creature in that area must make a Constitution saving throw.',
    damage: { diceExpression: '8d6', damageType: 'necrotic', scalingDice: '2d6' },
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'necrotic', 'constitution_save', 'sphere', 'area', 'costly_components'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 2d6 for each slot level above 6th.'
  },

  contingency: {
    id: 'contingency',
    name: 'Contingency',
    level: 6,
    school: 'evocation',
    castingTime: '10 minutes',
    range: 'Self',
    components: ['V', 'S', 'M'],
    materialComponent: 'a statuette of yourself carved from ivory and decorated with gems worth at least 1,500 gp',
    duration: '10 days',
    description: 'Choose a spell of 5th level or lower that you can cast, that has a casting time of 1 action, and that can target you. You cast that spell as part of casting contingency, expending spell slots for both.',
    concentration: false,
    ritual: false,
    classes: ['Wizard'],
    source: 'SRD 5.1',
    tags: ['utility', 'contingent_casting', 'self_only', 'costly_components', 'long_duration']
  },

  disintegrate: {
    id: 'disintegrate',
    name: 'Disintegrate',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a lodestone and a pinch of dust',
    duration: 'Instantaneous',
    description: 'A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force.',
    damage: { diceExpression: '10d6+40', damageType: 'force', scalingDice: '3d6' },
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'force', 'dexterity_save', 'disintegration', 'high_damage'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.'
  },

  eyebite: {
    id: 'eyebite',
    name: 'Eyebite',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: 'Self',
    components: ['V', 'S'],
    duration: 'Concentration, up to 1 minute',
    description: 'For the spell\'s duration, your eyes become an inky void imbued with dreadful power. One creature of your choice within 60 feet of you that you can see must succeed on a Wisdom saving throw or be affected by one of the following effects of your choice for the duration.',
    savingThrow: { ability: 'WIS', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['control', 'wisdom_save', 'concentration', 'multiple_effects', 'gaze']
  },

  fleshToStone: {
    id: 'flesh_to_stone',
    name: 'Flesh to Stone',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a pinch of lime, water, and earth',
    duration: 'Concentration, up to 1 minute',
    description: 'You attempt to turn one creature that you can see within range into stone. If the target\'s body is made of flesh, the creature must make a Constitution saving throw.',
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'petrification', 'constitution_save', 'concentration', 'incapacitation']
  },

  globeOfInvulnerability: {
    id: 'globe_of_invulnerability',
    name: 'Globe of Invulnerability',
    level: 6,
    school: 'abjuration',
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    components: ['V', 'S', 'M'],
    materialComponent: 'a glass or crystal bead that shatters when the spell ends',
    duration: 'Concentration, up to 1 minute',
    description: 'An immobile, faintly shimmering barrier springs into existence in a 10-foot radius around you and remains for the duration.',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['protection', 'spell_immunity', 'barrier', 'concentration'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the barrier blocks spells of one level higher for each slot level above 6th.'
  },

  harm: {
    id: 'harm',
    name: 'Harm',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    description: 'You unleash a virulent disease on a creature that you can see within range. The target must make a Constitution saving throw.',
    damage: { diceExpression: '14d6', damageType: 'necrotic', scalingDice: '0' },
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Cleric'],
    source: 'SRD 5.1',
    tags: ['damage', 'necrotic', 'constitution_save', 'disease', 'hit_point_maximum']
  },

  heal: {
    id: 'heal',
    name: 'Heal',
    level: 6,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    description: 'Choose a creature that you touch. The target regains 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target.',
    concentration: false,
    ritual: false,
    classes: ['Cleric', 'Druid'],
    source: 'SRD 5.1',
    tags: ['healing', 'high_healing', 'condition_removal', 'disease_cure']
  },

  massHaste: {
    id: 'mass_haste',
    name: 'Mass Haste',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a shaving of licorice root',
    duration: 'Concentration, up to 1 minute',
    description: 'Choose up to 6 willing creatures within range. Until the spell ends, each target\'s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['buff', 'speed', 'ac_bonus', 'extra_action', 'concentration', 'multiple_targets']
  },

  massSuggestion: {
    id: 'mass_suggestion',
    name: 'Mass Suggestion',
    level: 6,
    school: 'enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'M'],
    materialComponent: 'a snake\'s tongue and either a bit of honeycomb or a drop of sweet oil',
    duration: '24 hours',
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence up to twelve creatures of your choice that you can see within range and that can hear and understand you.',
    savingThrow: { ability: 'WIS', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['control', 'suggestion', 'wisdom_save', 'multiple_targets', 'long_duration']
  },

  moveEarth: {
    id: 'move_earth',
    name: 'Move Earth',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'an iron blade and a small bag containing a mixture of soils—clay, loam, and sand',
    duration: 'Concentration, up to 2 hours',
    description: 'Choose an area of terrain no larger than 40 feet on a side within range. You can reshape dirt, sand, or clay in the area in any manner you choose for the duration.',
    concentration: true,
    ritual: false,
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['utility', 'terrain_modification', 'earth', 'concentration', 'large_area']
  },

  sunbeam: {
    id: 'sunbeam',
    name: 'Sunbeam',
    level: 6,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    components: ['V', 'S', 'M'],
    materialComponent: 'a magnifying glass',
    duration: 'Concentration, up to 1 minute',
    description: 'A beam of brilliant light flashes out from your hand in a 5-foot-wide, 60-foot-long line. Each creature in the line must make a Constitution saving throw.',
    damage: { diceExpression: '6d8', damageType: 'radiant', scalingDice: '0' },
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'radiant', 'constitution_save', 'line', 'concentration', 'undead_vulnerability']
  },

  trueSeeing: {
    id: 'true_seeing',
    name: 'True Seeing',
    level: 6,
    school: 'divination',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'an ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell',
    duration: '1 hour',
    description: 'This spell gives the willing creature you touch the ability to see things as they actually are. For the duration, the creature has truesight, has a range of 120 feet.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['divination', 'truesight', 'detection', 'costly_components']
  },

  wallOfIce: {
    id: 'wall_of_ice',
    name: 'Wall of Ice',
    level: 6,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a small piece of quartz',
    duration: 'Concentration, up to 10 minutes',
    description: 'You create a wall of ice on a solid surface within range. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-square panels.',
    damage: { diceExpression: '10d6', damageType: 'cold', scalingDice: '0' },
    concentration: true,
    ritual: false,
    classes: ['Wizard'],
    source: 'SRD 5.1',
    tags: ['creation', 'wall', 'ice', 'cold', 'barrier', 'concentration']
  },

  windWalk: {
    id: 'wind_walk',
    name: 'Wind Walk',
    level: 6,
    school: 'transmutation',
    castingTime: '1 minute',
    range: '30 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'fire and holy water',
    duration: '8 hours',
    description: 'You and up to ten willing creatures you can see within range assume a gaseous form for the duration, appearing as wisps of cloud.',
    concentration: false,
    ritual: false,
    classes: ['Druid'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'gaseous_form', 'flight', 'multiple_targets', 'long_duration']
  },

  arcaneGate: {
    id: 'arcane_gate',
    name: 'Arcane Gate',
    level: 6,
    school: 'conjuration',
    castingTime: '1 action',
    range: '500 feet',
    components: ['V', 'S'],
    duration: 'Concentration, up to 10 minutes',
    description: 'You create linked teleportation portals that remain open for the duration.',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['conjuration', 'teleportation', 'portal', 'concentration']
  },

  bestowCurse: {
    id: 'bestow_curse_6',
    name: 'Bestow Curse',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S'],
    duration: 'Concentration, up to 1 minute',
    description: 'You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell.',
    savingThrow: { ability: 'WIS', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['necromancy', 'curse', 'wisdom_save', 'touch', 'concentration']
  },

  circleOfDeath: {
    id: 'circle_of_death',
    name: 'Circle of Death',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'the powder of a crushed black pearl worth at least 500 gp',
    duration: 'Instantaneous',
    description: 'A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range.',
    damage: { diceExpression: '8d6', damageType: 'necrotic', scalingDice: '2d6' },
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['necromancy', 'necrotic', 'constitution_save', 'sphere', 'costly_components'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 2d6 for each slot level above 6th.'
  },

  conjureFey: {
    id: 'conjure_fey',
    name: 'Conjure Fey',
    level: 6,
    school: 'conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: ['V', 'S'],
    duration: 'Concentration, up to 1 hour',
    description: 'You summon a fey creature of challenge rating 6 or lower, or a fey spirit that takes the form of a beast of challenge rating 6 or lower.',
    concentration: true,
    ritual: false,
    classes: ['Druid', 'Warlock'],
    source: 'SRD 5.1',
    tags: ['summoning', 'fey', 'large_creature', 'concentration'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the challenge rating increases by 1 for each slot level above 6th.'
  },

  contingency: {
    id: 'contingency',
    name: 'Contingency',
    level: 6,
    school: 'evocation',
    castingTime: '10 minutes',
    range: 'Self',
    components: ['V', 'S', 'M'],
    materialComponent: 'a statuette of yourself carved from ivory and decorated with gems worth at least 1,500 gp',
    duration: '10 days',
    description: 'Choose a spell of 5th level or lower that you can cast, that has a casting time of 1 action, and that can target you.',
    concentration: false,
    ritual: false,
    classes: ['Wizard'],
    source: 'SRD 5.1',
    tags: ['evocation', 'contingent', 'trigger', 'costly_components', 'long_duration']
  },

  createUndead: {
    id: 'create_undead',
    name: 'Create Undead',
    level: 6,
    school: 'necromancy',
    castingTime: '1 minute',
    range: '10 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'one clay pot filled with grave dirt, one clay pot filled with brackish water, and one 150 gp black onyx stone for each corpse',
    duration: 'Instantaneous',
    description: 'You can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids within range.',
    concentration: false,
    ritual: false,
    classes: ['Cleric', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['necromancy', 'undead', 'creation', 'night_only', 'costly_components'],
    upcastDescription: 'When you cast this spell using a 7th-level spell slot, you can animate or reassert control over four ghouls. When you cast this spell using an 8th-level spell slot, you can animate or reassert control over five ghouls or two ghasts or wights. When you cast this spell using a 9th-level spell slot, you can animate or reassert control over six ghouls, three ghasts or wights, or two mummies.'
  },

  disintegrate: {
    id: 'disintegrate',
    name: 'Disintegrate',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a lodestone and a pinch of dust',
    duration: 'Instantaneous',
    description: 'A thin green ray springs from your pointing finger to a target that you can see within range.',
    damage: { diceExpression: '10d6+40', damageType: 'force', scalingDice: '3d6' },
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'force', 'dexterity_save', 'object_destruction'],
    upcastDescription: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.'
  },

  eyebite: {
    id: 'eyebite',
    name: 'Eyebite',
    level: 6,
    school: 'necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: 'Concentration, up to 1 minute',
    description: 'For the spell\'s duration, your eyes become an inky void imbued with dreadful power.',
    savingThrow: { ability: 'WIS', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['necromancy', 'fear', 'charm', 'wisdom_save', 'concentration']
  },

  findThePath: {
    id: 'find_the_path',
    name: 'Find the Path',
    level: 6,
    school: 'divination',
    castingTime: '1 minute',
    range: 'Self',
    components: ['V', 'S', 'M'],
    materialComponent: 'a set of divinatory tools—such as bones, ivory sticks, cards, teeth, or carved runes—worth 100 gp and an object from the location you wish to find',
    duration: 'Concentration, up to 1 day',
    description: 'This spell allows you to find the shortest, most direct physical route to a specific fixed location that you are familiar with on the same plane of existence.',
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Druid'],
    source: 'SRD 5.1',
    tags: ['divination', 'navigation', 'path_finding', 'concentration', 'costly_components']
  },

  fleshToStone: {
    id: 'flesh_to_stone',
    name: 'Flesh to Stone',
    level: 6,
    school: 'transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a pinch of lime, water, and earth',
    duration: 'Concentration, up to 1 minute',
    description: 'You attempt to turn one creature that you can see within range into stone.',
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'petrification', 'constitution_save', 'concentration']
  },

  forbiddance: {
    id: 'forbiddance',
    name: 'Forbiddance',
    level: 6,
    school: 'abjuration',
    castingTime: '10 minutes',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a sprinkling of holy water, rare incense, and powdered ruby worth at least 1,000 gp',
    duration: '1 day',
    description: 'You create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 30 feet above the floor.',
    damage: { diceExpression: '5d10', damageType: 'radiant' },
    concentration: false,
    ritual: true,
    classes: ['Cleric'],
    source: 'SRD 5.1',
    tags: ['abjuration', 'warding', 'planar_travel', 'ritual', 'costly_components']
  },

  globeOfInvulnerability: {
    id: 'globe_of_invulnerability',
    name: 'Globe of Invulnerability',
    level: 6,
    school: 'abjuration',
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    components: ['V', 'S', 'M'],
    materialComponent: 'a glass or crystal bead that shatters when the spell ends',
    duration: 'Concentration, up to 1 minute',
    description: 'An immobile, faintly shimmering barrier springs into existence in a 10-foot radius around you and remains for the duration.',
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['abjuration', 'barrier', 'spell_immunity', 'concentration']
  },

  guardAndWards: {
    id: 'guards_and_wards',
    name: 'Guards and Wards',
    level: 6,
    school: 'abjuration',
    castingTime: '10 minutes',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'burning incense, a small measure of brimstone and oil, a knotted string, a small amount of umber hulk blood, and a small silver rod worth at least 10 gp',
    duration: '24 hours',
    description: 'You create a ward that protects up to 2,500 square feet of floor space (an area 50 feet square, or one hundred 5-foot squares or twenty-five 10-foot squares).',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['abjuration', 'warding', 'area_protection', 'long_duration', 'costly_components']
  },

  massScuggestion: {
    id: 'mass_suggestion',
    name: 'Mass Suggestion',
    level: 6,
    school: 'enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'M'],
    materialComponent: 'a snake\'s tongue and either a bit of honeycomb or a drop of sweet oil',
    duration: '24 hours',
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence up to twelve creatures of your choice that you can see within range and that can hear and understand you.',
    savingThrow: { ability: 'WIS', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['enchantment', 'suggestion', 'wisdom_save', 'multiple_targets', 'long_duration']
  }
};
