export const LEVEL_2_SPELLS = {
  holdPerson: {
    id: "hold_person",
    name: "Hold Person",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a small, straight piece of iron",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["control", "paralyzed", "wisdom_save", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.",
  },
  scorchingRay: {
    id: "scorching_ray",
    name: "Scorching Ray",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.",
    damage: { diceExpression: "2d6", damageType: "fire", scalingDice: "1d6" },
    attackRoll: true,
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "fire", "spell_attack", "multiple_rays"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.",
  },
  mistyStep: {
    id: "misty_step",
    name: "Misty Step",
    level: 2,
    school: "conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["movement", "teleport", "bonus_action"],
  },
  web: {
    id: "web",
    name: "Web",
    level: 2,
    school: "conjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a bit of spiderweb",
    duration: "Concentration, up to 1 hour",
    description:
      "You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area.",
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["control", "restrained", "dexterity_save", "concentration", "difficult_terrain"],
  },
  invisibility: {
    id: "invisibility",
    name: "Invisibility",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "an eyelash encased in gum arabic",
    duration: "Concentration, up to 1 hour",
    description:
      "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The spell ends for a target that attacks or casts a spell.",
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["stealth", "invisible", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
  },
  suggestion: {
    id: "suggestion",
    name: "Suggestion",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "M"],
    materialComponent: "a snake's tongue and either a bit of honeycomb or a drop of sweet oil",
    duration: "Concentration, up to 8 hours",
    description:
      "You suggest a course of activity (limited to a sentence or two) and magically influence a humanoid you can see within range that can hear and understand you. The suggestion must be worded in such a manner as to make the activity sound reasonable.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["social", "charm", "wisdom_save", "concentration"],
  },
  // Additional Level 2 Spells for Enterprise Implementation
  blindnessDeafness: {
    id: "blindness_deafness",
    name: "Blindness/Deafness",
    level: 2,
    school: "necromancy",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V"],
    duration: "1 minute",
    description:
      "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration.",
    savingThrow: { ability: "CON", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["debuff", "blinded", "deafened", "constitution_save"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
  },
  detectThoughts: {
    id: "detect_thoughts",
    name: "Detect Thoughts",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "a copper piece",
    duration: "Concentration, up to 1 minute",
    description:
      "For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["detection", "mind_reading", "wisdom_save", "concentration"],
  },
  heatMetal: {
    id: "heat_metal",
    name: "Heat Metal",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a piece of iron and a flame",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage when you cast the spell.",
    damage: { diceExpression: "2d8", damageType: "fire" },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Druid"],
    source: "SRD 5.1",
    tags: ["damage", "fire", "concentration", "metal_objects"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.",
  },
  levitate: {
    id: "levitate",
    name: "Levitate",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent:
      "either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end",
    duration: "Concentration, up to 10 minutes",
    description:
      "One creature or object of your choice that you can see within range rises vertically, up to 20 feet, and remains suspended there for the duration. The spell can levitate a target that weighs up to 500 pounds.",
    savingThrow: { ability: "CON", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["movement", "levitation", "constitution_save", "concentration"],
  },
  mirrorImage: {
    id: "mirror_image",
    name: "Mirror Image",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "1 minute",
    description:
      "Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it's impossible to track which image is real.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["defense", "illusion", "duplicates"],
  },
  spiritualWeapon: {
    id: "spiritual_weapon",
    name: "Spiritual Weapon",
    level: 2,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "1 minute",
    description:
      "You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon.",
    damage: { diceExpression: "1d8", damageType: "force", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false,
    ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["damage", "force", "spell_attack", "bonus_action", "spectral"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.",
  },
  shatter: {
    id: "shatter",
    name: "Shatter",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a chip of mica",
    duration: "Instantaneous",
    description:
      "A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw.",
    damage: { diceExpression: "3d8", damageType: "thunder", scalingDice: "1d8" },
    savingThrow: { ability: "CON", dc: 0 },
    areaOfEffect: { shape: "sphere", radius: 10 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "thunder", "constitution_save", "area_of_effect"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.",
  },
  acidArrow: {
    id: "acid_arrow",
    name: "Acid Arrow",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "90 feet",
    components: ["V", "S", "M"],
    materialComponent: "powdered rhubarb leaf and an adder's stomach",
    duration: "Instantaneous",
    description:
      "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn.",
    damage: { diceExpression: "4d4", damageType: "acid", scalingDice: "1d4" },
    attackRoll: true,
    concentration: false,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "acid", "spell_attack", "persistent_damage"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.",
  },
  alterSelf: {
    id: "alter_self",
    name: "Alter Self",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "Concentration, up to 1 hour",
    description:
      "You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell.",
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["transformation", "shapechange", "concentration", "utility"],
  },
  animalMessenger: {
    id: "animal_messenger",
    name: "Animal Messenger",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent: "a morsel of food",
    duration: "24 hours",
    description:
      "By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range.",
    concentration: false,
    ritual: true,
    classes: ["Bard", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["communication", "animal", "ritual", "utility", "beast"],
  },
  augury: {
    id: "augury",
    name: "Augury",
    level: 2,
    school: "divination",
    castingTime: "1 minute",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "specially marked sticks, bones, or similar tokens worth at least 25 gp",
    duration: "Instantaneous",
    description:
      "By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action.",
    concentration: false,
    ritual: true,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["divination", "fortune", "ritual", "costly_components"],
  },
  barkskin: {
    id: "barkskin",
    name: "Barkskin",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "a handful of oak bark",
    duration: "Concentration, up to 1 hour",
    description:
      "You touch a willing creature. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 16, regardless of what kind of armor it is wearing.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["protection", "ac_minimum", "concentration", "touch"],
  },
  beastSense: {
    id: "beast_sense",
    name: "Beast Sense",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Touch",
    components: ["S"],
    duration: "Concentration, up to 1 hour",
    description:
      "You touch a willing beast. For the duration of the spell, you can use your action to see through the beast's eyes and speak through the beast's mouth.",
    concentration: true,
    ritual: true,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["divination", "senses", "beast", "concentration", "ritual"],
  },
  blur: {
    id: "blur",
    name: "Blur",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "Self",
    components: ["V"],
    duration: "Concentration, up to 1 minute",
    description:
      "Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you.",
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["defense", "illusion", "disadvantage", "concentration"],
  },
  calmEmotions: {
    id: "calm_emotions",
    name: "Calm Emotions",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere centered on a point you choose within range must make a Charisma saving throw.",
    savingThrow: { ability: "CHA", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Cleric"],
    source: "SRD 5.1",
    tags: ["enchantment", "emotion", "charisma_save", "concentration", "area"],
  },
  continualFlame: {
    id: "continual_flame",
    name: "Continual Flame",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "ruby dust worth 50 gp, which the spell consumes",
    duration: "Until dispelled",
    description:
      "A flame, equivalent in brightness to a torch, springs forth from an object that you touch.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["light", "flame", "permanent", "costly_components", "touch"],
  },
  darkvision: {
    id: "darkvision",
    name: "Darkvision",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "either a pinch of dried carrot or an agate",
    duration: "8 hours",
    description: "You touch a willing creature to grant it the ability to see in the dark.",
    concentration: false,
    ritual: false,
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["enhancement", "vision", "darkvision", "touch", "long_duration"],
  },
  enhanceAbility: {
    id: "enhance_ability",
    name: "Enhance Ability",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "fur or a feather from a beast",
    duration: "Concentration, up to 1 hour",
    description:
      "You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects; the target gains that effect until the spell ends.",
    concentration: true,
    ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Sorcerer"],
    source: "SRD 5.1",
    tags: ["enhancement", "ability_score", "concentration", "touch", "buff"],
  },
  enthrall: {
    id: "enthrall",
    name: "Enthrall",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "1 minute",
    description:
      "You weave a distracting string of words, causing creatures of your choice that you can see within range and that can hear you to make a Wisdom saving throw.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Warlock"],
    source: "SRD 5.1",
    tags: ["enchantment", "charm", "wisdom_save", "distraction"],
  },
  findTraps: {
    id: "find_traps",
    name: "Find Traps",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You sense the presence of any trap within range that is within line of sight.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["detection", "traps", "divination", "utility"],
  },
  flameArrow: {
    id: "flame_arrow",
    name: "Flame Arrow",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "a piece of ammunition or a thrown weapon",
    duration: "Concentration, up to 1 hour",
    description:
      "You touch a quiver containing arrows or bolts. When a target is hit by a ranged weapon attack using a piece of ammunition drawn from the quiver, the target takes an extra 1d6 fire damage.",
    damage: { diceExpression: "1d6", damageType: "fire" },
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["enhancement", "fire", "ammunition", "concentration", "touch"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the number of pieces of ammunition you can affect increases by two for each slot level above 2nd.",
  },
  flamingSphere: {
    id: "flaming_sphere",
    name: "Flaming Sphere",
    level: 2,
    school: "conjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    materialComponent: "a bit of tallow, a pinch of brimstone, and a dusting of powdered iron",
    duration: "Concentration, up to 1 minute",
    description:
      "A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration.",
    damage: { diceExpression: "2d6", damageType: "fire", scalingDice: "1d6" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Druid", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "fire", "sphere", "dexterity_save", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.",
  },
  gentleRepose: {
    id: "gentle_repose",
    name: "Gentle Repose",
    level: 2,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a pinch of salt and a copper piece placed on each of the corpse's eyes, which must remain there for the duration",
    duration: "10 days",
    description:
      "You touch a corpse or other remains. For the duration, the target is protected from decay and can't become undead.",
    concentration: false,
    ritual: true,
    classes: ["Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "corpse", "preservation", "ritual", "touch"],
  },
  gustOfWind: {
    id: "gust_of_wind",
    name: "Gust of Wind",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-foot line)",
    components: ["V", "S", "M"],
    materialComponent: "a legume seed",
    duration: "Concentration, up to 1 minute",
    description:
      "A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell's duration.",
    savingThrow: { ability: "STR", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["evocation", "wind", "line", "strength_save", "concentration"],
  },
  lesserRestoration: {
    id: "lesser_restoration",
    name: "Lesser Restoration",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "You touch a creature and can end either one disease or one condition afflicting it.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    source: "SRD 5.1",
    tags: ["healing", "restoration", "disease", "condition", "touch"],
  },
  locateAnimalsOrPlants: {
    id: "locate_animals_or_plants",
    name: "Locate Animals or Plants",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "a bit of fur from a bloodhound",
    duration: "Instantaneous",
    description:
      "Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in your surroundings, you learn the direction and distance to the closest creature or plant of that kind within 5 miles.",
    concentration: false,
    ritual: true,
    classes: ["Bard", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["divination", "location", "beast", "plant", "ritual"],
  },
  locateObject: {
    id: "locate_object",
    name: "Locate Object",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "a forked twig",
    duration: "Concentration, up to 10 minutes",
    description:
      "Describe or name an object that is familiar to you. You sense the direction to the object's location, as long as that object is within 1,000 feet of you.",
    concentration: true,
    ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
    source: "SRD 5.1",
    tags: ["divination", "location", "object", "concentration"],
  },
  magicWeapon: {
    id: "magic_weapon",
    name: "Magic Weapon",
    level: 2,
    school: "transmutation",
    castingTime: "1 bonus action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Concentration, up to 1 hour",
    description:
      "You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus to attack rolls and damage rolls.",
    concentration: true,
    ritual: false,
    classes: ["Paladin", "Ranger"],
    source: "SRD 5.1",
    tags: ["enhancement", "weapon", "magic", "concentration", "bonus_action"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the bonus increases to +2. When you use a spell slot of 6th level or higher, the bonus increases to +3.",
  },
  moonbeam: {
    id: "moonbeam",
    name: "Moonbeam",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S", "M"],
    materialComponent: "several seeds of any moonseed plant and a piece of opalescent feldspar",
    duration: "Concentration, up to 1 minute",
    description:
      "A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range.",
    damage: { diceExpression: "2d10", damageType: "radiant", scalingDice: "1d10" },
    savingThrow: { ability: "CON", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Druid"],
    source: "SRD 5.1",
    tags: ["damage", "radiant", "cylinder", "constitution_save", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.",
  },
  passwithoutTrace: {
    id: "pass_without_trace",
    name: "Pass without Trace",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "ashes from a burned leaf of mistletoe and a sprig of spruce",
    duration: "Concentration, up to 1 hour",
    description:
      "A veil of shadows and silence radiates from you, masking you and your companions from detection.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["stealth", "concealment", "concentration", "group"],
  },
  protectionFromPoison: {
    id: "protection_from_poison",
    name: "Protection from Poison",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "1 hour",
    description:
      "You touch a creature. If it is poisoned, you neutralize the poison. If more than one poison afflicts the target, you neutralize one poison that you know is present.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Druid", "Paladin", "Ranger"],
    source: "SRD 5.1",
    tags: ["protection", "poison", "neutralize", "touch"],
  },
  rayOfEnfeeblement: {
    id: "ray_of_enfeeblement",
    name: "Ray of Enfeeblement",
    level: 2,
    school: "necromancy",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target.",
    attackRoll: true,
    concentration: true,
    ritual: false,
    classes: ["Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["debuff", "necrotic", "spell_attack", "concentration", "weakness"],
  },
  ropetrick: {
    id: "rope_trick",
    name: "Rope Trick",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "powdered corn extract and a twisted loop of parchment",
    duration: "1 hour",
    description:
      "You touch a length of rope that is up to 60 feet long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground.",
    concentration: false,
    ritual: false,
    classes: ["Wizard"],
    source: "SRD 5.1",
    tags: ["utility", "rope", "extradimensional", "touch"],
  },
  seeInvisibility: {
    id: "see_invisibility",
    name: "See Invisibility",
    level: 2,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "a pinch of talc and a small sprinkling of powdered silver",
    duration: "1 hour",
    description:
      "For the duration, you see invisible creatures and objects as if they were visible, and you can see into the Ethereal Plane.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["detection", "invisible", "ethereal", "vision"],
  },
  spike_growth: {
    id: "spike_growth",
    name: "Spike Growth",
    level: 2,
    school: "transmutation",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "seven sharp thorns or seven small twigs, each sharpened to a point",
    duration: "Concentration, up to 10 minutes",
    description:
      "The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns.",
    damage: { diceExpression: "2d4", damageType: "piercing" },
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["area_control", "piercing", "difficult_terrain", "concentration"],
  },
  summonBeast: {
    id: "summon_beast",
    name: "Summon Beast",
    level: 2,
    school: "conjuration",
    castingTime: "1 action",
    range: "90 feet",
    components: ["V", "S", "M"],
    materialComponent:
      "a feather, tuft of fur, and fish tail inside a gilded acorn worth at least 200 gp",
    duration: "Concentration, up to 1 hour",
    description:
      "You call forth a bestial spirit. It manifests in an unoccupied space that you can see within range.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["summoning", "beast", "concentration", "costly_components"],
    upcastDescription:
      "When you cast this spell using a spell slot of 3rd level or higher, use the higher level wherever the spell's level appears in the stat block.",
  },
  zone_of_truth: {
    id: "zone_of_truth",
    name: "Zone of Truth",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "10 minutes",
    description:
      "You create a magical zone that guards against deception in a 15-foot-radius sphere centered on a point of your choice within range.",
    savingThrow: { ability: "CHA", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Paladin"],
    source: "SRD 5.1",
    tags: ["enchantment", "truth", "charisma_save", "zone", "social"],
  },
  warding_bond: {
    id: "warding_bond",
    name: "Warding Bond",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a pair of platinum rings worth at least 50 gp each, which you and the target must wear for the duration",
    duration: "1 hour",
    description:
      "This spell wards a willing creature you touch and creates a mystic connection between you and the target until the spell ends.",
    concentration: false,
    ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["protection", "bond", "shared_damage", "costly_components", "touch"],
  },
  silence: {
    id: "silence",
    name: "Silence",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 10 minutes",
    description:
      "For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range.",
    concentration: true,
    ritual: true,
    classes: ["Bard", "Cleric", "Ranger"],
    source: "SRD 5.1",
    tags: ["illusion", "silence", "area", "concentration", "ritual"],
  },
};
//# sourceMappingURL=level2.js.map
