import type { SRDSpell } from '../spells';

export const LEVEL_7_SPELLS: Record<string, SRDSpell> = {
  delayedBlastFireball: {
    id: 'delayed_blast_fireball',
    name: 'Delayed Blast Fireball',
    level: 7,
    school: 'evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a tiny ball of bat guano and sulfur',
    duration: 'Concentration, up to 1 minute',
    description: 'A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration.',
    damage: { diceExpression: '12d6', damageType: 'fire', scalingDice: '1d6' },
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'fire', 'dexterity_save', 'sphere', 'delayed', 'concentration'],
    upcastDescription: 'When you cast this spell using a spell slot of 8th level or higher, the damage increases by 1d6 for each slot level above 7th.'
  },

  etherealness: {
    id: 'etherealness',
    name: 'Etherealness',
    level: 7,
    school: 'transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: ['V', 'S'],
    duration: '8 hours',
    description: 'You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['utility', 'ethereal_plane', 'phasing', 'long_duration']
  },

  fingerOfDeath: {
    id: 'finger_of_death',
    name: 'Finger of Death',
    level: 7,
    school: 'necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    description: 'You send negative energy coursing through a creature that you can see within range, causing it searing pain.',
    damage: { diceExpression: '7d8+30', damageType: 'necrotic', scalingDice: '1d8' },
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'necrotic', 'constitution_save', 'high_damage', 'zombie_creation'],
    upcastDescription: 'When you cast this spell using a spell slot of 8th level or higher, the damage increases by 1d8 for each slot level above 7th.'
  },

  firestorm: {
    id: 'firestorm',
    name: 'Firestorm',
    level: 7,
    school: 'evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    description: 'A storm made up of sheets of roaring flame appears in a location you choose within range. The area of the storm consists of up to ten 10-foot cubes, which you can arrange as you wish.',
    damage: { diceExpression: '7d10', damageType: 'fire', scalingDice: '1d10' },
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Cleric', 'Druid', 'Sorcerer'],
    source: 'SRD 5.1',
    tags: ['damage', 'fire', 'dexterity_save', 'multiple_cubes', 'area', 'configurable'],
    upcastDescription: 'When you cast this spell using a spell slot of 8th level or higher, the damage increases by 1d10 for each slot level above 7th.'
  },

  forcecage: {
    id: 'forcecage',
    name: 'Forcecage',
    level: 7,
    school: 'evocation',
    castingTime: '1 action',
    range: '100 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'ruby dust worth 1,500 gp',
    duration: '1 hour',
    description: 'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range.',
    savingThrow: { ability: 'CHA', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['control', 'force', 'imprisonment', 'charisma_save', 'costly_components']
  },

  magnificentMansion: {
    id: 'magnificent_mansion',
    name: 'Magnificent Mansion',
    level: 7,
    school: 'conjuration',
    castingTime: '1 minute',
    range: '300 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp',
    duration: '24 hours',
    description: 'You conjure an extradimensional dwelling in range that lasts for the duration. You choose where its one entrance is located.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['utility', 'extradimensional', 'shelter', 'long_duration', 'costly_components']
  },

  planeShift: {
    id: 'plane_shift',
    name: 'Plane Shift',
    level: 7,
    school: 'conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence',
    duration: 'Instantaneous',
    description: 'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence.',
    savingThrow: { ability: 'CHA', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['teleportation', 'planar_travel', 'charisma_save', 'multiple_targets', 'costly_components']
  },

  prismaticSpray: {
    id: 'prismatic_spray',
    name: 'Prismatic Spray',
    level: 7,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Self (60-foot cone)',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    description: 'Eight multicolored rays of light flash from your hand. Each ray is a different color and has a different power and purpose.',
    concentration: false,
    ritual: false,
    classes: ['Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['damage', 'multiple_effects', 'cone', 'random', 'varied_damage_types']
  },

  projectImage: {
    id: 'project_image',
    name: 'Project Image',
    level: 7,
    school: 'illusion',
    castingTime: '1 action',
    range: '500 miles',
    components: ['V', 'S', 'M'],
    materialComponent: 'a small replica of you made from materials worth at least 5 gp',
    duration: 'Concentration, up to 1 day',
    description: 'You create an illusory copy of yourself that lasts for the duration. The copy can appear at any location within range that you have seen before.',
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['illusion', 'projection', 'long_range', 'concentration', 'costly_components']
  },

  regenerate: {
    id: 'regenerate',
    name: 'Regenerate',
    level: 7,
    school: 'transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a prayer wheel and holy water',
    duration: '1 hour',
    description: 'You touch a creature and stimulate its natural healing ability. The target regains 4d8 + 15 hit points.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Druid'],
    source: 'SRD 5.1',
    tags: ['healing', 'regeneration', 'limb_restoration', 'ongoing_healing']
  },

  resurrection: {
    id: 'resurrection',
    name: 'Resurrection',
    level: 7,
    school: 'necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a diamond worth at least 1,000 gp, which the spell consumes',
    duration: 'Instantaneous',
    description: 'You touch a dead creature that has been dead for no more than a century, that didn\'t die of old age, and that isn\'t undead.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric'],
    source: 'SRD 5.1',
    tags: ['necromancy', 'resurrection', 'death_reversal', 'costly_components']
  },

  reverseGravity: {
    id: 'reverse_gravity',
    name: 'Reverse Gravity',
    level: 7,
    school: 'transmutation',
    castingTime: '1 action',
    range: '100 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a lodestone and iron filings',
    duration: 'Concentration, up to 1 minute',
    description: 'This spell reverses gravity in a 50-foot-radius, 100-foot high cylinder centered on a point within range.',
    savingThrow: { ability: 'DEX', dc: 0 },
    concentration: true,
    ritual: false,
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'gravity', 'dexterity_save', 'cylinder', 'area', 'concentration']
  },

  sequester: {
    id: 'sequester',
    name: 'Sequester',
    level: 7,
    school: 'transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes',
    duration: 'Until dispelled',
    description: 'By means of this spell, a willing creature or an object can be hidden away, safe from detection for the duration.',
    concentration: false,
    ritual: false,
    classes: ['Wizard'],
    source: 'SRD 5.1',
    tags: ['utility', 'hiding', 'stasis', 'permanent', 'costly_components']
  },

  simulacrum: {
    id: 'simulacrum',
    name: 'Simulacrum',
    level: 7,
    school: 'illusion',
    castingTime: '12 hours',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'snow or ice in quantities sufficient to made a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature\'s body placed inside the snow or ice; and powdered ruby worth 1,500 gp, sprinkled over the duplicate and consumed by the spell',
    duration: 'Until dispelled',
    description: 'You shape an illusory duplicate of one beast or humanoid that is within range for the entire casting time of the spell.',
    concentration: false,
    ritual: false,
    classes: ['Wizard'],
    source: 'SRD 5.1',
    tags: ['illusion', 'duplicate', 'permanent', 'costly_components', 'long_casting']
  },

  symbolOfStunning: {
    id: 'symbol_of_stunning',
    name: 'Symbol of Stunning',
    level: 7,
    school: 'enchantment',
    castingTime: '1 minute',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes',
    duration: 'Until dispelled or triggered',
    description: 'When you cast this spell, you inscribe a harmful symbol either on a surface or within an object that can later hold the symbol.',
    savingThrow: { ability: 'CON', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['enchantment', 'symbol', 'stunning', 'constitution_save', 'trap', 'costly_components']
  },

  teleport: {
    id: 'teleport',
    name: 'Teleport',
    level: 7,
    school: 'conjuration',
    castingTime: '1 action',
    range: '10 feet',
    components: ['V'],
    duration: 'Instantaneous',
    description: 'This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['teleportation', 'long_distance', 'multiple_targets', 'familiarity_based']
  },

  etherealness: {
    id: 'etherealness',
    name: 'Etherealness',
    level: 7,
    school: 'transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: ['V', 'S'],
    duration: '8 hours',
    description: 'You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane.',
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'ethereal', 'plane_shift', 'long_duration']
  },

  mordenkaiensSword: {
    id: 'mordenkainens_sword',
    name: 'Mordenkainen\'s Sword',
    level: 7,
    school: 'evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materialComponent: 'a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp',
    duration: 'Concentration, up to 1 minute',
    description: 'You create a sword-shaped plane of force that hovers within range.',
    damage: { diceExpression: '3d10', damageType: 'force', scalingDice: '0' },
    attackRoll: true,
    concentration: true,
    ritual: false,
    classes: ['Bard', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['evocation', 'force', 'weapon', 'concentration', 'costly_components']
  },

  planeShift: {
    id: 'plane_shift',
    name: 'Plane Shift',
    level: 7,
    school: 'conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence',
    duration: 'Instantaneous',
    description: 'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence.',
    savingThrow: { ability: 'CHA', dc: 0 },
    concentration: false,
    ritual: false,
    classes: ['Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    source: 'SRD 5.1',
    tags: ['conjuration', 'planar_travel', 'charisma_save', 'costly_components', 'multiple_targets']
  },

  regenerate: {
    id: 'regenerate',
    name: 'Regenerate',
    level: 7,
    school: 'transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materialComponent: 'a prayer wheel and holy water',
    duration: '1 hour',
    description: 'You touch a creature and stimulate its natural healing ability.',
    healing: { diceExpression: '4d8+15', scalingDice: '0' },
    concentration: false,
    ritual: false,
    classes: ['Bard', 'Cleric', 'Druid'],
    source: 'SRD 5.1',
    tags: ['transmutation', 'healing', 'regeneration', 'limb_restoration', 'touch']
  }
};
