import type { SRDSpell } from "../spells";

export const LEVEL_3_SPELLS: Record<string, SRDSpell> = {
  fireball: {
    id: "fireball",
    name: "Fireball",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "a tiny ball of bat guano and sulfur",
    duration: "Instantaneous",
    description:
      "A bright flash of fire expands from your fingertips to a chosen point within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw.",
    damage: { diceExpression: "8d6", damageType: "fire", scalingDice: "1d6" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "fire", "dexterity_save", "sphere", "area"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
  },

  lightningBolt: {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (100-foot line)",
    components: ["V", "S", "M"],
    materialComponent: "a bit of fur and a rod of amber, crystal, or glass",
    duration: "Instantaneous",
    description:
      "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw.",
    damage: { diceExpression: "8d6", damageType: "lightning", scalingDice: "1d6" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["damage", "lightning", "dexterity_save", "line", "area"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
  },

  counterspell: {
    id: "counterspell",
    name: "Counterspell",
    level: 3,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "60 feet",
    components: ["S"],
    duration: "Instantaneous",
    description:
      "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["utility", "counter", "reaction"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.",
  },

  dispelMagic: {
    id: "dispel_magic",
    name: "Dispel Magic",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["utility", "dispel"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell's level is equal to or less than the level of the spell slot you used.",
  },

  fly: {
    id: "fly",
    name: "Fly",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "a wing feather from any bird",
    duration: "Concentration, up to 10 minutes",
    description:
      "You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.",
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["movement", "flight", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.",
  },

  haste: {
    id: "haste",
    name: "Haste",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent: "a shaving of licorice root",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.",
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["buff", "speed", "ac_bonus", "concentration"],
  },

  slow: {
    id: "slow",
    name: "Slow",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S", "M"],
    materialComponent: "a drop of molasses",
    duration: "Concentration, up to 1 minute",
    description:
      "You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["debuff", "wisdom_save", "concentration", "movement_reduction"],
  },

  animateDead: {
    id: "animate_dead",
    name: "Animate Dead",
    level: 3,
    school: "necromancy",
    castingTime: "1 minute",
    range: "10 feet",
    components: ["V", "S", "M"],
    materialComponent: "a drop of blood, a piece of flesh, and a pinch of bone dust",
    duration: "Instantaneous",
    description:
      "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "undead", "summoning", "minion"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd.",
  },

  blink: {
    id: "blink",
    name: "Blink",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "1 minute",
    description:
      "Roll a d20 at the end of each of your turns for the duration of the spell. On a roll of 11 or higher, you vanish from your current plane of existence and appear in the Ethereal Plane.",
    concentration: false,
    ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "ethereal", "defense", "random"],
  },

  callLightning: {
    id: "call_lightning",
    name: "Call Lightning",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 10 minutes",
    description:
      "A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see within range directly above you.",
    damage: { diceExpression: "3d10", damageType: "lightning", scalingDice: "1d10" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Druid"],
    source: "SRD 5.1",
    tags: ["damage", "lightning", "dexterity_save", "concentration", "storm"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d10 for each slot level above 3rd.",
  },

  clairvoyance: {
    id: "clairvoyance",
    name: "Clairvoyance",
    level: 3,
    school: "divination",
    castingTime: "10 minutes",
    range: "1 mile",
    components: ["V", "S", "M"],
    materialComponent:
      "a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing",
    duration: "Concentration, up to 10 minutes",
    description:
      "You create an invisible sensor within range in a location familiar to you or in an obvious location that is unfamiliar to you.",
    concentration: true,
    ritual: false,
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["divination", "scrying", "sensor", "concentration", "costly_components"],
  },

  conjureAnimals: {
    id: "conjure_animals",
    name: "Conjure Animals",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Concentration, up to 1 hour",
    description:
      "You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["summoning", "beasts", "fey", "concentration", "multiple_creatures"],
    upcastDescription:
      "When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 5th-level slot, three times as many with a 7th-level slot, and four times as many with a 9th-level slot.",
  },

  createFoodAndWater: {
    id: "create_food_and_water",
    name: "Create Food and Water",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "You create 45 pounds of food and 30 gallons of water on the ground or in containers within range, enough to sustain up to fifteen humanoids or five steeds for 24 hours.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Paladin"],
    source: "SRD 5.1",
    tags: ["conjuration", "food", "water", "utility", "survival"],
  },

  daylight: {
    id: "daylight",
    name: "Daylight",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "1 hour",
    description:
      "A 60-foot-radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"],
    source: "SRD 5.1",
    tags: ["light", "sphere", "utility", "darkness_dispel"],
  },

  fear: {
    id: "fear",
    name: "Fear",
    level: 3,
    school: "illusion",
    castingTime: "1 action",
    range: "Self (30-foot cone)",
    components: ["V", "S", "M"],
    materialComponent: "a white feather or the heart of a hen",
    duration: "Concentration, up to 1 minute",
    description:
      "You project a phantasmagorical image of a creature's worst fears. Each creature in a 30-foot cone must succeed on a Wisdom saving throw or drop whatever it is holding and become frightened for the duration.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["illusion", "frightened", "wisdom_save", "cone", "concentration"],
  },

  hypnoticPattern: {
    id: "hypnotic_pattern",
    name: "Hypnotic Pattern",
    level: 3,
    school: "illusion",
    castingTime: "1 action",
    range: "120 feet",
    components: ["S", "M"],
    materialComponent:
      "a glowing stick of incense or a crystal vial filled with phosphorescent material",
    duration: "Concentration, up to 1 minute",
    description:
      "You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw.",
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["illusion", "charmed", "incapacitated", "wisdom_save", "concentration"],
  },

  majorImage: {
    id: "major_image",
    name: "Major Image",
    level: 3,
    school: "illusion",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S", "M"],
    materialComponent: "a bit of fleece",
    duration: "Concentration, up to 10 minutes",
    description:
      "You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 20-foot cube.",
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["illusion", "image", "concentration", "large_area"],
    upcastDescription:
      "When you cast this spell using a spell slot of 6th level or higher, the spell lasts until dispelled, without requiring your concentration.",
  },

  massHealingWord: {
    id: "mass_healing_word",
    name: "Mass Healing Word",
    level: 3,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 feet",
    components: ["V"],
    duration: "Instantaneous",
    description:
      "As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier.",
    healing: { diceExpression: "1d4", scalingDice: "1d4" },
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric"],
    source: "SRD 5.1",
    tags: ["healing", "bonus_action", "multiple_targets"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.",
  },

  nondetection: {
    id: "nondetection",
    name: "Nondetection",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent:
      "a pinch of diamond dust worth 25 gp sprinkled over the target, which the spell consumes",
    duration: "8 hours",
    description: "For the duration, you hide a target that you touch from divination magic.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Ranger", "Wizard"],
    source: "SRD 5.1",
    tags: ["abjuration", "stealth", "divination_block", "costly_components"],
  },

  plantGrowth: {
    id: "plant_growth",
    name: "Plant Growth",
    level: 3,
    school: "transmutation",
    castingTime: "1 action or 8 hours",
    range: "150 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "This spell channels vitality into plants within a specific area. There are two possible uses for the spell, granting either immediate or long-term benefits.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["transmutation", "plants", "growth", "difficult_terrain", "utility"],
  },

  protectionFromEnergy: {
    id: "protection_from_energy",
    name: "Protection from Energy",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Concentration, up to 1 hour",
    description:
      "For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.",
    concentration: true,
    ritual: false,
    classes: ["Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["protection", "resistance", "energy_damage", "concentration"],
  },

  removeDisease: {
    id: "remove_disease",
    name: "Remove Disease",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Instantaneous",
    description:
      "You touch a creature and can end either one disease or one condition afflicting it.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Druid", "Paladin", "Ranger"],
    source: "SRD 5.1",
    tags: ["healing", "disease", "restoration", "touch"],
  },

  revivify: {
    id: "revivify",
    name: "Revivify",
    level: 3,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "diamonds worth 300 gp, which the spell consumes",
    duration: "Instantaneous",
    description:
      "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.",
    concentration: false,
    ritual: false,
    classes: ["Cleric", "Paladin"],
    source: "SRD 5.1",
    tags: ["necromancy", "resurrection", "costly_components", "touch"],
  },

  sendingMessage: {
    id: "sending_message",
    name: "Sending",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "Unlimited",
    components: ["V", "S", "M"],
    materialComponent: "a short piece of fine copper wire",
    duration: "1 round",
    description:
      "You send a short message of twenty-five words or less to a creature with which you are familiar.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Wizard"],
    source: "SRD 5.1",
    tags: ["communication", "message", "unlimited_range", "telepathic"],
  },

  sleetStorm: {
    id: "sleet_storm",
    name: "Sleet Storm",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    materialComponent: "a pinch of dust and a few drops of water",
    duration: "Concentration, up to 1 minute",
    description:
      "Until the spell ends, freezing rain and sleet fall in a 20-foot-tall cylinder with a 40-foot radius centered on a point you choose within range.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["weather", "difficult_terrain", "concentration", "cylinder", "cold"],
  },

  speakWithAnimals: {
    id: "speak_with_animals_3",
    name: "Speak with Animals",
    level: 3,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "10 minutes",
    description:
      "You gain the ability to comprehend and verbally communicate with beasts for the duration.",
    concentration: false,
    ritual: true,
    classes: ["Bard", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["communication", "beast", "ritual", "social"],
  },

  speakWithDead: {
    id: "speak_with_dead",
    name: "Speak with Dead",
    level: 3,
    school: "necromancy",
    castingTime: "1 action",
    range: "10 feet",
    components: ["V", "S", "M"],
    materialComponent: "burning incense",
    duration: "10 minutes",
    description:
      "You grant the semblance of life and intelligence to a corpse of your choice within range, allowing it to answer the questions you pose.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric"],
    source: "SRD 5.1",
    tags: ["necromancy", "communication", "corpse", "information"],
  },

  speakWithPlants: {
    id: "speak_with_plants",
    name: "Speak with Plants",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Self (30-foot radius)",
    components: ["V", "S"],
    duration: "10 minutes",
    description:
      "You imbue plants within 30 feet of you with limited sentience and animation, giving them the ability to communicate with you and follow your simple commands.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["transmutation", "plants", "communication", "animation"],
  },

  spiritGuardians: {
    id: "spirit_guardians",
    name: "Spirit Guardians",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "Self (15-foot radius)",
    components: ["V", "S", "M"],
    materialComponent: "a holy symbol",
    duration: "Concentration, up to 10 minutes",
    description:
      "You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration.",
    damage: { diceExpression: "3d8", damageType: "radiant", scalingDice: "1d8" },
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.1",
    tags: ["conjuration", "spirits", "damage", "radiant", "wisdom_save", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.",
  },

  stinkingCloud: {
    id: "stinking_cloud",
    name: "Stinking Cloud",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "90 feet",
    components: ["V", "S", "M"],
    materialComponent: "a rotten egg or several skunk cabbage leaves",
    duration: "Concentration, up to 1 minute",
    description:
      "You create a 20-foot-radius sphere of yellow, nauseating gas centered on a point within range.",
    savingThrow: { ability: "CON", dc: 0 },
    concentration: true,
    ritual: false,
    classes: ["Bard", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["conjuration", "poison", "incapacitated", "constitution_save", "concentration"],
  },

  tongues: {
    id: "tongues",
    name: "Tongues",
    level: 3,
    school: "divination",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "M"],
    materialComponent: "a small clay model of a ziggurat",
    duration: "1 hour",
    description:
      "This spell grants the creature you touch the ability to understand any spoken language it hears.",
    concentration: false,
    ritual: false,
    classes: ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["divination", "language", "communication", "comprehension"],
  },

  vampiricTouch: {
    id: "vampiric_touch",
    name: "Vampiric Touch",
    level: 3,
    school: "necromancy",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description:
      "The touch of your shadow-wreathed hand can siphon life force from others to heal your wounds.",
    damage: { diceExpression: "3d6", damageType: "necrotic", scalingDice: "1d6" },
    attackRoll: true,
    healing: { diceExpression: "half_damage", scalingDice: "half_damage" },
    concentration: true,
    ritual: false,
    classes: ["Warlock", "Wizard"],
    source: "SRD 5.1",
    tags: ["necromancy", "damage", "necrotic", "healing", "life_drain", "concentration"],
    upcastDescription:
      "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
  },

  waterBreathing: {
    id: "water_breathing",
    name: "Water Breathing",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent: "a short reed or piece of straw",
    duration: "24 hours",
    description:
      "This spell grants up to ten willing creatures you can see within range the ability to breathe underwater until the spell ends.",
    concentration: false,
    ritual: true,
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    source: "SRD 5.1",
    tags: ["transmutation", "breathing", "underwater", "utility", "ritual"],
  },

  waterWalk: {
    id: "water_walk",
    name: "Water Walk",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S", "M"],
    materialComponent: "a piece of cork or light wood",
    duration: "1 hour",
    description:
      "This spell grants the ability to move across any liquid surface such as water, acid, mud, snow, quicksand, or lava as if it were harmless solid ground.",
    concentration: false,
    ritual: true,
    classes: ["Cleric", "Druid", "Ranger", "Sorcerer"],
    source: "SRD 5.1",
    tags: ["transmutation", "movement", "liquid_surface", "utility", "ritual"],
  },

  windWall: {
    id: "wind_wall",
    name: "Wind Wall",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S", "M"],
    materialComponent: "a tiny fan and a feather of exotic origin",
    duration: "Concentration, up to 1 minute",
    description:
      "A wall of strong wind rises from the ground at a point you choose within range. You can make the wall up to 50 feet long, 15 feet high, and 1 foot thick.",
    concentration: true,
    ritual: false,
    classes: ["Druid", "Ranger"],
    source: "SRD 5.1",
    tags: ["evocation", "wall", "wind", "protection", "concentration"],
  },
};
