export const LEVEL_4_SPELLS = {
    banishment: {
        id: "banishment",
        name: "Banishment",
        level: 4,
        school: "abjuration",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "an item distasteful to the target",
        duration: "Concentration, up to 1 minute",
        description: "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished.",
        savingThrow: { ability: "CHA", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["control", "banishment", "charisma_save", "concentration", "planar"],
        upcastDescription: "When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.",
    },
    blight: {
        id: "blight",
        name: "Blight",
        level: 4,
        school: "necromancy",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw.",
        damage: { diceExpression: "8d8", damageType: "necrotic", scalingDice: "1d8" },
        savingThrow: { ability: "CON", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Druid", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "necrotic", "constitution_save", "plant_vulnerability"],
        upcastDescription: "When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.",
    },
    confusion: {
        id: "confusion",
        name: "Confusion",
        level: 4,
        school: "enchantment",
        castingTime: "1 action",
        range: "90 feet",
        components: ["V", "S", "M"],
        materialComponent: "three nut shells",
        duration: "Concentration, up to 1 minute",
        description: "This spell assaults and twists creatures' minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or be affected by it.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["control", "confusion", "wisdom_save", "concentration", "sphere", "area"],
    },
    conjureMinorElementals: {
        id: "conjure_minor_elementals",
        name: "Conjure Minor Elementals",
        level: 4,
        school: "conjuration",
        castingTime: "1 minute",
        range: "90 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 hour",
        description: "You summon elementals that appear in unoccupied spaces that you can see within range. Choose one of the following options for what appears: One elemental of challenge rating 2 or lower, Two elementals of challenge rating 1 or lower, Four elementals of challenge rating 1/2 or lower, Eight elementals of challenge rating 1/4 or lower.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Wizard"],
        source: "SRD 5.1",
        tags: ["summoning", "elemental", "concentration", "multiple_options"],
        upcastDescription: "When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 6th-level slot and three times as many with an 8th-level slot.",
    },
    conjureWoodlandBeings: {
        id: "conjure_woodland_beings",
        name: "Conjure Woodland Beings",
        level: 4,
        school: "conjuration",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "one holly berry per creature summoned",
        duration: "Concentration, up to 1 hour",
        description: "You summon fey creatures that appear in unoccupied spaces that you can see within range. Choose one of the following options for what appears: One fey creature of challenge rating 2 or lower, Two fey creatures of challenge rating 1 or lower, Four fey creatures of challenge rating 1/2 or lower, Eight fey creatures of challenge rating 1/4 or lower.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["summoning", "fey", "concentration", "multiple_options"],
        upcastDescription: "When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 6th-level slot and three times as many with an 8th-level slot.",
    },
    dimensionDoor: {
        id: "dimension_door",
        name: "Dimension Door",
        level: 4,
        school: "conjuration",
        castingTime: "1 action",
        range: "500 feet",
        components: ["V"],
        duration: "Instantaneous",
        description: "You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["teleportation", "movement", "utility", "long_range"],
    },
    divination: {
        id: "divination",
        name: "Divination",
        level: 4,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes",
        duration: "Instantaneous",
        description: "Your magic and an offering put you in contact with a god or a god's servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days.",
        concentration: false,
        ritual: true,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["divination", "information", "ritual", "divine_contact", "costly_components"],
    },
    dominateBeast: {
        id: "dominate_beast",
        name: "Dominate Beast",
        level: 4,
        school: "enchantment",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Druid", "Sorcerer"],
        source: "SRD 5.1",
        tags: ["control", "charm", "beast_only", "wisdom_save", "concentration"],
        upcastDescription: "When you cast this spell with a 5th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 6th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 7th level or higher, the duration is concentration, up to 8 hours.",
    },
    fabricate: {
        id: "fabricate",
        name: "Fabricate",
        level: 4,
        school: "transmutation",
        castingTime: "10 minutes",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Instantaneous",
        description: "You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool.",
        concentration: false,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "crafting", "transmutation", "material_conversion"],
    },
    fireShield: {
        id: "fire_shield",
        name: "Fire Shield",
        level: 4,
        school: "evocation",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a bit of phosphorus or a firefly",
        duration: "10 minutes",
        description: "Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius and dim light for an additional 10 feet. You can end the spell early by using an action to dismiss it.",
        concentration: false,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["protection", "fire", "cold_resistance", "damage_shield", "light"],
    },
    freedomOfMovement: {
        id: "freedom_of_movement",
        name: "Freedom of Movement",
        level: 4,
        school: "abjuration",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "a leather strap, bound around the arm or a similar appendage",
        duration: "1 hour",
        description: "You touch a willing creature. For the duration, the target's movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target's speed nor cause the target to be paralyzed or restrained.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Ranger"],
        source: "SRD 5.1",
        tags: ["utility", "movement", "immunity", "condition_prevention"],
    },
    giantInsect: {
        id: "giant_insect",
        name: "Giant Insect",
        level: 4,
        school: "transmutation",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 10 minutes",
        description: "You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms for the duration.",
        concentration: true,
        ritual: false,
        classes: ["Druid"],
        source: "SRD 5.1",
        tags: ["transmutation", "enhancement", "insect", "concentration", "multiple_targets"],
    },
    greaterInvisibility: {
        id: "greater_invisibility",
        name: "Greater Invisibility",
        level: 4,
        school: "illusion",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person.",
        concentration: true,
        ritual: false,
        classes: ["Bard", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "invisibility", "concentration", "combat_invisibility"],
    },
    guardianOfFaith: {
        id: "guardian_of_faith",
        name: "Guardian of Faith",
        level: 4,
        school: "conjuration",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V"],
        duration: "8 hours",
        description: "A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of your deity.",
        damage: { diceExpression: "20", damageType: "radiant", scalingDice: "0" },
        concentration: false,
        ritual: false,
        classes: ["Cleric"],
        source: "SRD 5.1",
        tags: ["conjuration", "guardian", "radiant", "area_denial", "long_duration"],
    },
    hallucinatoryTerrain: {
        id: "hallucinatory_terrain",
        name: "Hallucinatory Terrain",
        level: 4,
        school: "illusion",
        castingTime: "10 minutes",
        range: "300 feet",
        components: ["V", "S", "M"],
        materialComponent: "a stone, a twig, and a bit of green plant",
        duration: "24 hours",
        description: "You make natural terrain in a 150-foot cube in range look, sound, and smell like some other sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain.",
        concentration: false,
        ritual: false,
        classes: ["Bard", "Druid", "Warlock", "Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "terrain", "large_area", "long_duration", "deception"],
    },
    iceStorm: {
        id: "ice_storm",
        name: "Ice Storm",
        level: 4,
        school: "evocation",
        castingTime: "1 action",
        range: "300 feet",
        components: ["V", "S", "M"],
        materialComponent: "a pinch of dust and a few drops of water",
        duration: "Instantaneous",
        description: "A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw.",
        damage: { diceExpression: "2d8", damageType: "bludgeoning", scalingDice: "1d8" },
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: false,
        ritual: false,
        classes: ["Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: [
            "damage",
            "bludgeoning",
            "cold",
            "dexterity_save",
            "cylinder",
            "area",
            "difficult_terrain",
        ],
        upcastDescription: "When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.",
    },
    locateCreature: {
        id: "locate_creature",
        name: "Locate Creature",
        level: 4,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a bit of fur from a bloodhound",
        duration: "Concentration, up to 1 hour",
        description: "Describe or name a creature that is familiar to you. You sense the direction to the creature's location, as long as that creature is within 1,000 feet of you.",
        concentration: true,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "detection", "tracking", "concentration", "long_range"],
    },
    polymorph: {
        id: "polymorph",
        name: "Polymorph",
        level: 4,
        school: "transmutation",
        castingTime: "1 action",
        range: "60 feet",
        components: ["V", "S", "M"],
        materialComponent: "a caterpillar cocoon",
        duration: "Concentration, up to 1 hour",
        description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["transmutation", "shapechange", "wisdom_save", "concentration", "beast_form"],
    },
    stoneShape: {
        id: "stone_shape",
        name: "Stone Shape",
        level: 4,
        school: "transmutation",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "soft clay, which must be worked into roughly the desired shape of the stone object",
        duration: "Instantaneous",
        description: "You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose.",
        concentration: false,
        ritual: false,
        classes: ["Cleric", "Druid", "Wizard"],
        source: "SRD 5.1",
        tags: ["utility", "transmutation", "stone", "shaping", "construction"],
    },
    stoneskin: {
        id: "stoneskin",
        name: "Stoneskin",
        level: 4,
        school: "abjuration",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S", "M"],
        materialComponent: "diamond dust worth 100 gp, which the spell consumes",
        duration: "Concentration, up to 1 hour",
        description: "This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["protection", "resistance", "physical_damage", "concentration", "costly_components"],
    },
    wallOfFire: {
        id: "wall_of_fire",
        name: "Wall of Fire",
        level: 4,
        school: "evocation",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small piece of phosphorus",
        duration: "Concentration, up to 1 minute",
        description: "You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick.",
        damage: { diceExpression: "5d8", damageType: "fire", scalingDice: "1d8" },
        concentration: true,
        ritual: false,
        classes: ["Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["damage", "fire", "wall", "area_denial", "concentration"],
        upcastDescription: "When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.",
    },
    arcaneEye: {
        id: "arcane_eye",
        name: "Arcane Eye",
        level: 4,
        school: "divination",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a bit of bat fur",
        duration: "Concentration, up to 1 hour",
        description: "You create an invisible, magical eye within range that hovers in the air for the duration.",
        concentration: true,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "scrying", "invisible", "sensor", "concentration"],
    },
    compulsion: {
        id: "compulsion",
        name: "Compulsion",
        level: 4,
        school: "enchantment",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw.",
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Bard"],
        source: "SRD 5.1",
        tags: ["enchantment", "movement_control", "wisdom_save", "concentration"],
    },
    controlWater: {
        id: "control_water",
        name: "Control Water",
        level: 4,
        school: "transmutation",
        castingTime: "1 action",
        range: "300 feet",
        components: ["V", "S", "M"],
        materialComponent: "a drop of water and a pinch of dust",
        duration: "Concentration, up to 10 minutes",
        description: "Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side.",
        concentration: true,
        ritual: false,
        classes: ["Cleric", "Druid", "Wizard"],
        source: "SRD 5.1",
        tags: ["transmutation", "water", "control", "environmental", "concentration"],
    },
    deathWard: {
        id: "death_ward",
        name: "Death Ward",
        level: 4,
        school: "abjuration",
        castingTime: "1 action",
        range: "Touch",
        components: ["V", "S"],
        duration: "8 hours",
        description: "You touch a creature and grant it a measure of protection from death.",
        concentration: false,
        ritual: false,
        classes: ["Cleric", "Paladin"],
        source: "SRD 5.1",
        tags: ["protection", "death_prevention", "touch", "long_duration"],
    },
    locate: {
        id: "locate_creature",
        name: "Locate Creature",
        level: 4,
        school: "divination",
        castingTime: "1 action",
        range: "Self",
        components: ["V", "S", "M"],
        materialComponent: "a bit of fur from a bloodhound",
        duration: "Concentration, up to 1 hour",
        description: "Describe or name a creature that is familiar to you. You sense the direction to the creature's location, as long as that creature is within 1,000 feet of you.",
        concentration: true,
        ritual: false,
        classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
        source: "SRD 5.1",
        tags: ["divination", "tracking", "location", "concentration"],
    },
    otilukesResilientSphere: {
        id: "otilukes_resilient_sphere",
        name: "Otiluke's Resilient Sphere",
        level: 4,
        school: "evocation",
        castingTime: "1 action",
        range: "30 feet",
        components: ["V", "S", "M"],
        materialComponent: "a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic",
        duration: "Concentration, up to 1 minute",
        description: "A sphere of shimmering force encloses a creature or object of Large size or smaller within range.",
        savingThrow: { ability: "DEX", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["evocation", "force", "protection", "sphere", "dexterity_save", "concentration"],
    },
    phantasmalKiller: {
        id: "phantasmal_killer",
        name: "Phantasmal Killer",
        level: 4,
        school: "illusion",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S"],
        duration: "Concentration, up to 1 minute",
        description: "You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to that creature.",
        damage: { diceExpression: "4d10", damageType: "psychic", scalingDice: "1d10" },
        savingThrow: { ability: "WIS", dc: 0 },
        concentration: true,
        ritual: false,
        classes: ["Wizard"],
        source: "SRD 5.1",
        tags: ["illusion", "fear", "psychic", "wisdom_save", "concentration"],
        upcastDescription: "When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d10 for each slot level above 4th.",
    },
    wallOfStone: {
        id: "wall_of_stone",
        name: "Wall of Stone",
        level: 4,
        school: "evocation",
        castingTime: "1 action",
        range: "120 feet",
        components: ["V", "S", "M"],
        materialComponent: "a small block of granite",
        duration: "Concentration, up to 10 minutes",
        description: "A nonmagical wall of solid stone springs into existence at a point you choose within range.",
        concentration: true,
        ritual: false,
        classes: ["Druid", "Sorcerer", "Wizard"],
        source: "SRD 5.1",
        tags: ["evocation", "wall", "stone", "barrier", "concentration"],
    },
};
//# sourceMappingURL=level4.js.map