services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: vtt
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d vtt"]
      interval: 10s
      timeout: 5s
      retries: 3
    mem_limit: 512m
    cpus: 0.5

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: devpass
    ports: ["6379:6379"]
    volumes: [redisdata:/data]
    command: redis-server --requirepass devpass
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    mem_limit: 256m
    cpus: 0.25

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devpass
    ports: ["9000:9000", "9090:9090"]
    volumes: [miniodata:/data]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 256m
    cpus: 0.25
volumes:
  pgdata:
  redisdata:
  miniodata:
