services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: vtt
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: devpass
    ports: ["6379:6379"]
    volumes: [redisdata:/data]
    command: redis-server --requirepass devpass

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devpass
    ports: ["9000:9000", "9090:9090"]
    volumes: [miniodata:/data]
volumes:
  pgdata:
  redisdata:
  miniodata:
