[build]
  # Base directory for the build
  base = ""
  
  # Build command for the client app using pnpm
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build --filter=@vtt/client"
  
  # Publish directory - where Vite outputs the built client files
  publish = "apps/client/dist"

[build.environment]
  # Node version for builds
  NODE_VERSION = "22"
  # Enable pnpm
  PNPM_VERSION = "9.12.2"

[[redirects]]
  # SPA redirect for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets
    Cache-Control = "public, max-age=31536000, immutable"
