name: "Setup Native Dependencies"
description: "Install native build dependencies required for Node.js native modules"
inputs:
  extra-packages:
    description: "Additional packages to install"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: apt-cache-${{ runner.os }}-${{ hashFiles('**/package*.json') }}
        restore-keys: |
          apt-cache-${{ runner.os }}-

    - name: Install native build dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "Installing native build dependencies..."
        sudo apt-get update

        # Core build tools
        PACKAGES="nasm yasm build-essential libpng-dev"

        # Add extra packages if provided
        if [ -n "${{ inputs.extra-packages }}" ]; then
          PACKAGES="$PACKAGES ${{ inputs.extra-packages }}"
        fi

        echo "Installing: $PACKAGES"
        sudo apt-get install -y $PACKAGES

        echo "✅ Native dependencies installed successfully"
