name: "Setup Node.js with pnpm"
description: "Install Node.js, enable pnpm (Corepack fallback) and optionally install system packages"
author: "VTT DevOps"
inputs:
  node-version:
    description: "Node.js version to install"
    required: false
    default: "22"
  pnpm-version:
    description: "pnpm version to install or activate"
    required: false
    default: "9.12.2"
  check-latest:
    description: "Request the latest minor/patch for the Node.js version"
    required: false
    default: "true"
  install-system-packages:
    description: "Whitespace-separated list of apt packages to install before Node setup"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      if: inputs.install-system-packages != ''
      shell: bash
      env:
        APT_PACKAGES: ${{ inputs['install-system-packages'] }}
      run: |
        set -euo pipefail
        if command -v sudo >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y $APT_PACKAGES
        elif command -v apt-get >/dev/null 2>&1; then
          apt-get update
          apt-get install -y $APT_PACKAGES
        else
          echo "apt-get is not available on this runner"
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
        check-latest: ${{ inputs['check-latest'] == 'true' }}

    - name: Enable pnpm
      shell: bash
      env:
        PNPM_VERSION: ${{ inputs['pnpm-version'] }}
      run: |
        set -euo pipefail
        if command -v corepack >/dev/null 2>&1; then
          corepack enable
          corepack prepare pnpm@$PNPM_VERSION --activate
        else
          echo "corepack not found; installing pnpm globally via npm"
          npm install -g pnpm@$PNPM_VERSION
        fi
        if ! command -v pnpm >/dev/null 2>&1; then
          echo "pnpm not found after Corepack activation; installing via npm"
          npm install -g pnpm@$PNPM_VERSION
        fi

    - name: Verify versions
      shell: bash
      run: |
        set -euo pipefail
        node --version
        pnpm --version
