apiVersion: v1
kind: ConfigMap
metadata:
  name: vtt-config
  namespace: vtt
  labels:
    app.kubernetes.io/name: vtt-config
    app.kubernetes.io/part-of: vtt

data:
  # --- Server HTTP config ---
  PORT: "8080"
  JSON_LIMIT_BYTES: "1000000"

  # CORS configuration
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,OPTIONS,PUT,DELETE"
  CORS_HEADERS: "Content-Type,Authorization,X-Trace-ID,X-Request-ID"

  # Security headers
  HSTS: "true"
  CSP: "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"

  # Rate limiting (token bucket per IP)
  RATE_LIMIT_WINDOW_MS: "1000"
  RATE_LIMIT_MAX: "50"

  # WebSocket simulation toggles (server-side ECS demo)
  SIM_ENABLE: "false"
  SIM_N: "1000"
  SIM_BOUNDS: "2000"
  SIM_TICK: "12"

  # External endpoints
  MINIO_ENDPOINT: "http://minio.default.svc.cluster.local:9000"
