# checkov:skip=CKV_K8S_43: Image digest is enforced by CI/CD at deploy time
# checkov:skip=CKV_K8S_35: Using secrets as env vars is acceptable for migration jobs
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: vtt
  labels:
    app.kubernetes.io/name: db-migrate
    app.kubernetes.io/part-of: vtt
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-migrate
        app.kubernetes.io/part-of: vtt
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: ghcr.io/weningerii/vtt-server:main
          imagePullPolicy: Always
          command: ["sh", "-lc", "prisma migrate deploy --schema apps/server/prisma/schema.prisma"]
          envFrom:
            - configMapRef:
                name: vtt-config
                optional: true
            - secretRef:
                name: vtt-secrets
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
