apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  labels:
    app.kubernetes.io/part-of: vtt
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
