apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: client-pdb
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/part-of: vtt
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: client
