apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vtt
  name: vtt-server-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
  resourceNames: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vtt
  name: vtt-client-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vtt-server-binding
  namespace: vtt
subjects:
- kind: ServiceAccount
  name: server
  namespace: vtt
roleRef:
  kind: Role
  name: vtt-server-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vtt-client-binding
  namespace: vtt
subjects:
- kind: ServiceAccount
  name: client
  namespace: vtt
roleRef:
  kind: Role
  name: vtt-client-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: vtt
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/vtt-server-role
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: vtt
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/vtt-client-role
automountServiceAccountToken: false
