apiVersion: v1
kind: Secret
metadata:
  name: vtt-secrets
  namespace: vtt
  labels:
    app.kubernetes.io/part-of: vtt
stringData:
  # Required
  DATABASE_URL: ""
  MINIO_ROOT_USER: ""
  MINIO_ROOT_PASSWORD: ""

  # AI provider keys (optional)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""
  OPENROUTER_API_KEY: ""
  STABILITY_API_KEY: ""
