apiVersion: v1
kind: LimitRange
metadata:
  name: vtt-security-limits
  namespace: vtt
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
      ephemeral-storage: "100Mi"
    max:
      cpu: "2"
      memory: "2Gi"
      ephemeral-storage: "10Gi"
    min:
      cpu: "10m"
      memory: "32Mi"
      ephemeral-storage: "50Mi"
  - type: Pod
    max:
      cpu: "4"
      memory: "4Gi"
      ephemeral-storage: "20Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vtt-resource-quota
  namespace: vtt
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    requests.ephemeral-storage: "10Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    limits.ephemeral-storage: "50Gi"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "5"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: vtt-image-security
  annotations:
    policies.kyverno.io/title: VTT Image Security
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-image-tag
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - vtt
      validate:
        message: "Images must not use 'latest' tag"
        pattern:
          spec:
            containers:
            - name: "*"
              image: "!*:latest"
    
    - name: require-image-digest
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - vtt
      validate:
        message: "Images should use digest for immutability"
        anyPattern:
        - spec:
            containers:
            - name: "*"
              image: "*@sha256:*"
        - spec:
            containers:
            - name: "*"
              image: "ghcr.io/YOUR_ORG/*:*"
    
    - name: disallow-host-namespaces
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - vtt
      validate:
        message: "Host namespaces are not allowed"
        pattern:
          spec:
            =(hostNetwork): "false"
            =(hostIPC): "false"
            =(hostPID): "false"
