apiVersion: v1
kind: Namespace
metadata:
  name: vtt-production
  labels:
    name: vtt-production
    environment: production
    app.kubernetes.io/name: vtt-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: terraform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vtt-production-quota
  namespace: vtt-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vtt-production-limits
  namespace: vtt-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
