apiVersion: v1
kind: Secret
metadata:
  name: vtt-secrets
  namespace: vtt-production
  labels:
    app.kubernetes.io/name: vtt-platform
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials (to be populated by external secret operator)
  DB_USERNAME: ""
  DB_PASSWORD: ""
  
  # Redis auth token
  REDIS_AUTH_TOKEN: ""
  
  # JWT secrets
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
  JWT_EMAIL_SECRET: ""
  JWT_PASSWORD_RESET_SECRET: ""
  
  # Encryption keys
  ENCRYPTION_KEY: ""
  COOKIE_SECRET: ""
  
  # Third-party API keys
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  
  # OAuth secrets
  GOOGLE_CLIENT_SECRET: ""
  GITHUB_CLIENT_SECRET: ""
  
  # Email service
  SMTP_PASSWORD: ""
  SENDGRID_API_KEY: ""
  
  # Monitoring
  SENTRY_DSN: ""
  DATADOG_API_KEY: ""
  
  # AWS credentials (if not using IRSA)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: vtt-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vtt-external-secrets
  namespace: vtt-production
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: vtt-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: vtt-production/database
      property: password
  - secretKey: DB_USERNAME
    remoteRef:
      key: vtt-production/database
      property: username
  - secretKey: REDIS_AUTH_TOKEN
    remoteRef:
      key: vtt-production/redis
      property: auth-token
  - secretKey: JWT_ACCESS_SECRET
    remoteRef:
      key: vtt-production/jwt
      property: access-secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: vtt-production/jwt
      property: refresh-secret
  - secretKey: STRIPE_SECRET_KEY
    remoteRef:
      key: vtt-production/stripe
      property: secret-key
  - secretKey: STRIPE_WEBHOOK_SECRET
    remoteRef:
      key: vtt-production/stripe
      property: webhook-secret
