# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI (Optimized)

permissions:
  contents: read

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Turbo environment - conditionally set based on secrets availability
  TURBO_REMOTE_ONLY: false

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages || 'false' }}
      apps: ${{ steps.filter.outputs.apps || 'false' }}
      services: ${{ steps.filter.outputs.services || 'false' }}
      e2e: ${{ steps.filter.outputs.e2e || 'false' }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            packages:
              - 'packages/**'
            apps:
              - 'apps/**'
            services:
              - 'services/**'
            e2e:
              - 'e2e/**'
              - 'playwright.config.ts'

  lint-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
          install-system-packages: "libpng-dev libpng16-16 libpng-tools build-essential nasm yasm"
      - uses: ./.github/actions/install-deps
        with:
          ensure-native-deps: "true"
          prefer-offline: "true"
      - name: Lint (parallel with typecheck dependencies)
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          pnpm turbo lint --cache-dir=.turbo
      - name: Typecheck (with dependencies built)
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          # Typecheck depends on "^build" in turbo.json so this builds deps first
          pnpm turbo typecheck --cache-dir=.turbo

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [lint-and-typecheck]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
          install-system-packages: "libpng-dev libpng16-16 libpng-tools build-essential nasm yasm"
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - uses: ./.github/actions/install-deps
        with:
          ensure-native-deps: "true"
          prefer-offline: "true"
      - name: Generate Prisma client
        run: pnpm db:gen
      - name: Build with turbo
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: pnpm turbo build --cache-dir=.turbo

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
          install-system-packages: "libpng-dev libpng16-16 libpng-tools build-essential nasm yasm"
      - uses: ./.github/actions/install-deps
        with:
          ensure-native-deps: "true"
          prefer-offline: "true"
      - name: Run tests with coverage (shard ${{ matrix.shard }}/4)
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          mkdir -p .nyc_output coverage
          pnpm nyc pnpm turbo test --cache-dir=.turbo -- --shard=${{ matrix.shard }}/4
          ls -la .nyc_output || echo "Warning: .nyc_output directory is empty or missing"
          cp -r .nyc_output coverage/ || echo "No .nyc_output to copy"
          if [ ! -d "coverage/.nyc_output" ] || [ -z "$(ls -A coverage/.nyc_output 2>/dev/null)" ]; then
            echo "Creating placeholder coverage data"
            mkdir -p coverage/.nyc_output
            echo '{}' > coverage/.nyc_output/placeholder.json
          fi
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.shard }}
          path: |
            coverage/
            .nyc_output
          if-no-files-found: warn

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [build, changes]
    if: needs.changes.outputs.e2e == 'true' || needs.changes.outputs.apps == 'true'
    strategy:
      matrix:
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
          install-system-packages: "libpng-dev libpng16-16 libpng-tools build-essential nasm yasm"
      - uses: ./.github/actions/install-deps
        with:
          ensure-native-deps: "true"
          prefer-offline: "true"
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps
      - name: Run E2E tests (shard ${{ matrix.shard }}/2)
        run: pnpm test:e2e --shard=${{ matrix.shard }}/2
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright-report/

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
      - name: Upload SARIF as artifact (forked PRs)
        if: ${{ always() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-sarif
          path: trivy-results.sarif
      - name: Run npm audit
        run: |
          npm audit --audit-level=high --production
        continue-on-error: true
      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --config .audit-ci.json
        continue-on-error: true
