# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
      - name: Upload SARIF as artifact (forked PRs)
        if: ${{ always() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-sarif
          path: trivy-results.sarif
      - name: Run npm audit
        run: |
          npm audit --audit-level=high --production
        continue-on-error: true
      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --config .audit-ci.json
        continue-on-error: true

  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
      - name: Install libpng-dev
        run: sudo apt-get update && sudo apt-get install -y libpng-dev
      - uses: ./.github/actions/install-deps
      - name: Check license compliance
        run: node scripts/license-check.js

  build:
    runs-on: ubuntu-latest
    needs: [security, license-compliance]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
      - name: Install libpng-dev
        run: sudo apt-get update && sudo apt-get install -y libpng-dev
      - uses: ./.github/actions/install-deps
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
