# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
      - name: Setup native dependencies
        uses: ./.github/actions/setup-native-deps
      - uses: ./.github/actions/install-deps

      - name: Debug workspace for Trivy
        run: |
          echo "=== Current directory contents ==="
          ls -la
          echo "=== Disk space ==="
          df -h
          echo "=== Memory usage ==="
          free -h

      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          # Add additional configuration to help with potential issues
          timeout: "10m"
        env:
          TRIVY_DEBUG: true

      - name: Check if Trivy results exist
        id: check-trivy
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "trivy-results-exist=true" >> $GITHUB_OUTPUT
            echo "Trivy results file exists"
          else
            echo "trivy-results-exist=false" >> $GITHUB_OUTPUT
            echo "Trivy results file does not exist"
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ steps.check-trivy.outputs.trivy-results-exist == 'true' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Upload SARIF as artifact (forked PRs)
        if: ${{ steps.check-trivy.outputs.trivy-results-exist == 'true' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-sarif
          path: trivy-results.sarif
      - name: Run pnpm audit
        run: |
          pnpm audit --audit-level high --prod
        continue-on-error: true
      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --config .audit-ci.json
        continue-on-error: true

  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
      - name: Setup native dependencies
        uses: ./.github/actions/setup-native-deps
      - uses: ./.github/actions/install-deps
      - name: Check license compliance
        run: node scripts/license-check.js

  build:
    runs-on: ubuntu-latest
    needs: [security, license-compliance]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "20"
          pnpm-version: "9.12.2"
      - name: Setup native dependencies
        uses: ./.github/actions/setup-native-deps
      - uses: ./.github/actions/install-deps
      - name: Build
        run: pnpm run build
      - name: Lint (continue on error)
        run: pnpm run lint
        continue-on-error: true
      - name: Test
        run: pnpm run test
